INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('김비서가 왜 그럴까','What''s Wrong with Secretary Kim',ARRAY['김비서가 왜 그럴까','What''s Wrong with Secretary Kim','김비서가왜그럴까']::text[],2018,'TVN (Southeast Asia)',ARRAY['로맨스','코미디']::text[],'published'),
('더 킹 : 영원의 군주','The King: Eternal Monarch',ARRAY['더 킹 : 영원의 군주','The King: Eternal Monarch','더킹:영원의군주']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('로봇이 아니야','I''m Not a Robot',ARRAY['로봇이 아니야','I''m Not a Robot','로봇이아니야']::text[],2017,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('더블유','W',ARRAY['더블유','W']::text[],2016,'MBC',ARRAY['Drama']::text[],'published'),
('오 나의 귀신님','Oh My Ghostess',ARRAY['오 나의 귀신님','Oh My Ghostess','오나의귀신님']::text[],2015,'tvN',ARRAY['Drama']::text[],'published'),
('프로듀사','Producer',ARRAY['프로듀사','Producer']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('주몽','Jumong',ARRAY['주몽','Jumong']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('응답하라 1988','Reply 1988',ARRAY['응답하라 1988','Reply 1988','응답하라1988']::text[],2015,'tvN',ARRAY['로맨스','가족','코미디']::text[],'published'),
('드림하이','Dream High',ARRAY['드림하이','Dream High']::text[],2011,'KBS2',ARRAY['청춘','음악']::text[],'published'),
('겨울연가','Winter Sonata',ARRAY['겨울연가','Winter Sonata']::text[],2002,'KBS2',ARRAY['로맨스']::text[],'published'),
('어쩌다 발견한 하루','Extraordinary You',ARRAY['어쩌다 발견한 하루','Extraordinary You','어쩌다발견한하루']::text[],2019,'MBC',ARRAY['Drama']::text[],'published'),
('당신이 잠든 사이에','While You Were Sleeping',ARRAY['당신이 잠든 사이에','While You Were Sleeping','당신이잠든사이에']::text[],2017,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('구르미 그린 달빛','Love in the Moonlight',ARRAY['구르미 그린 달빛','Love in the Moonlight','구르미그린달빛']::text[],2016,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('역도요정 김복주','Weightlifting Fairy Kim Bok-Joo',ARRAY['역도요정 김복주','Weightlifting Fairy Kim Bok-Joo','역도요정김복주']::text[],2016,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('하이바이, 마마!','Hi Bye, Mama!',ARRAY['하이바이, 마마!','Hi Bye, Mama!','하이바이,마마!']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('이태원 클라쓰','Itaewon Class',ARRAY['이태원 클라쓰','Itaewon Class','이태원클라쓰']::text[],2020,'JTBC',ARRAY['드라마','청춘']::text[],'published'),
('시크릿 가든','Secret Garden',ARRAY['시크릿 가든','Secret Garden','시크릿가든']::text[],2010,'SBS',ARRAY['판타지','로맨스']::text[],'published'),
('커피프린스 1호점','The 1st Shop of Coffee Prince',ARRAY['커피프린스 1호점','The 1st Shop of Coffee Prince','커피프린스1호점']::text[],2007,'MBC',ARRAY['로맨스','코미디']::text[],'published'),
('종이의 집: 공동경제구역','Money Heist: Korea - Joint Economic Area',ARRAY['종이의 집: 공동경제구역','Money Heist: Korea - Joint Economic Area','종이의집:공동경제구역']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('지옥','Hellbound',ARRAY['지옥','Hellbound']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('미스터 션샤인','Mr. Sunshine',ARRAY['미스터 션샤인','Mr. Sunshine','미스터션샤인']::text[],2018,'tvN',ARRAY['사극','로맨스']::text[],'published'),
('화유기','A Korean Odyssey',ARRAY['화유기','A Korean Odyssey']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('힘쎈여자 도봉순','Strong Woman Do Bong-soon',ARRAY['힘쎈여자 도봉순','Strong Woman Do Bong-soon','힘쎈여자도봉순']::text[],2017,'JTBC',ARRAY['Drama']::text[],'published'),
('화랑','Hwarang: The Poet Warrior Youth',ARRAY['화랑','Hwarang: The Poet Warrior Youth']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('스위트홈','Sweet Home',ARRAY['스위트홈','Sweet Home']::text[],2020,NULL,ARRAY['Drama']::text[],'published'),
('피노키오','Pinocchio',ARRAY['피노키오','Pinocchio']::text[],2014,'Seoul Broadcasting System',ARRAY['로맨스','드라마']::text[],'published'),
('넌 내게 반했어','Heartstrings',ARRAY['넌 내게 반했어','Heartstrings','넌내게반했어']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('선덕여왕','Queen Seondeok',ARRAY['선덕여왕','Queen Seondeok']::text[],2009,'MBC',ARRAY['Drama']::text[],'published'),
('눈물의 여왕','Queen of Tears',ARRAY['눈물의 여왕','Queen of Tears','눈물의여왕']::text[],2024,'tvN',ARRAY['로맨스','드라마']::text[],'published'),
('환혼','Alchemy of Souls',ARRAY['환혼','Alchemy of Souls']::text[],2022,'tvN',ARRAY['판타지','액션']::text[],'published'),
('사내맞선','Business Proposal',ARRAY['사내맞선','Business Proposal']::text[],2022,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('갯마을 차차차','Hometown Cha-Cha-Cha',ARRAY['갯마을 차차차','Hometown Cha-Cha-Cha','갯마을차차차']::text[],2021,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('마이 네임','My Name',ARRAY['마이 네임','My Name','마이네임']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('시그널','Signal',ARRAY['시그널','Signal']::text[],2016,'tvN',ARRAY['스릴러','범죄']::text[],'published'),
('그녀는 예뻤다','She Was Pretty',ARRAY['그녀는 예뻤다','She Was Pretty','그녀는예뻤다']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('기황후','Empress Ki',ARRAY['기황후','Empress Ki']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('너의 목소리가 들려','I Can Hear Your Voice',ARRAY['너의 목소리가 들려','I Can Hear Your Voice','너의목소리가들려']::text[],2013,'SBS',ARRAY['Drama']::text[],'published'),
('주군의 태양','Master''s Sun',ARRAY['주군의 태양','Master''s Sun','주군의태양']::text[],2013,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('동이','Dong Yi',ARRAY['동이','Dong Yi']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('장난스런 키스','Playful Kiss',ARRAY['장난스런 키스','Playful Kiss','장난스런키스']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('미남이시네요','You''re Beautiful',ARRAY['미남이시네요','You''re Beautiful']::text[],2009,'TBS Television',ARRAY['Drama']::text[],'published'),
('이상한 변호사 우영우','Extraordinary Attorney Woo',ARRAY['이상한 변호사 우영우','Extraordinary Attorney Woo','이상한변호사우영우']::text[],2022,'Netflix',ARRAY['법률','드라마']::text[],'published'),
('악의 꽃','Flower of Evil',ARRAY['악의 꽃','Flower of Evil','악의꽃']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('남자친구','Encounter',ARRAY['남자친구','Encounter']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('닥터스','The Doctors',ARRAY['닥터스','The Doctors']::text[],2016,'SBS',ARRAY['Drama']::text[],'published'),
('힐러','Healer',ARRAY['힐러','Healer']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('시티헌터','City Hunter',ARRAY['시티헌터','City Hunter']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('단, 하나의 사랑','Angel''s Last Mission: Love',ARRAY['단, 하나의 사랑','Angel''s Last Mission: Love','단,하나의사랑']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('진심이 닿다','Touch Your Heart',ARRAY['진심이 닿다','Touch Your Heart','진심이닿다']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('내 아이디는 강남미인','My ID is Gangnam Beauty',ARRAY['내 아이디는 강남미인','My ID is Gangnam Beauty','내아이디는강남미인']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published'),
('후아유 : 학교 2015','Who Are You: School 2015',ARRAY['후아유 : 학교 2015','Who Are You: School 2015','후아유:학교2015']::text[],2015,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('굿 닥터','Good Doctor',ARRAY['굿 닥터','Good Doctor','굿닥터']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('내 여자친구는 구미호','My Girlfriend Is a Nine-Tailed Fox',ARRAY['내 여자친구는 구미호','My Girlfriend Is a Nine-Tailed Fox','내여자친구는구미호']::text[],2010,'SBS',ARRAY['Drama']::text[],'published'),
('개인의 취향','Personal Taste',ARRAY['개인의 취향','Personal Taste','개인의취향']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('궁','Princess Hours',ARRAY['궁','Princess Hours']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내 남편과 결혼해줘','Marry My Husband',ARRAY['내 남편과 결혼해줘','Marry My Husband','내남편과결혼해줘']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('너도 인간이니','Are You Human?',ARRAY['너도 인간이니','Are You Human?','너도인간이니']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('함부로 애틋하게','Uncontrollably Fond',ARRAY['함부로 애틋하게','Uncontrollably Fond','함부로애틋하게']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('아이리스','Iris',ARRAY['아이리스','Iris']::text[],2009,'KBS2',ARRAY['Drama']::text[],'published'),
('마이걸','My Girl',ARRAY['마이걸','My Girl']::text[],2005,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('풀하우스','Full House',ARRAY['풀하우스','Full House']::text[],2004,'KBS2',ARRAY['Drama']::text[],'published'),
('폭싹 속았수다','When Life Gives You Tangerines',ARRAY['폭싹 속았수다','When Life Gives You Tangerines','폭싹속았수다']::text[],2025,'Netflix',ARRAY['가족','로맨스']::text[],'published'),
('더 글로리','The Glory',ARRAY['더 글로리','The Glory','더글로리']::text[],2022,'Netflix',ARRAY['스릴러','복수']::text[],'published'),
('슬기로운 의사생활','Hospital Playlist',ARRAY['슬기로운 의사생활','Hospital Playlist','슬기로운의사생활']::text[],2020,'tvN',ARRAY['의료','드라마']::text[],'published'),
('SKY 캐슬','SKY Castle',ARRAY['SKY 캐슬','SKY Castle','SKY캐슬']::text[],2018,'JTBC',ARRAY['드라마','스릴러']::text[],'published'),
('수상한 파트너','Suspicious Partner',ARRAY['수상한 파트너','Suspicious Partner','수상한파트너']::text[],2017,'SBS',ARRAY['Drama']::text[],'published'),
('마녀보감','Secret Healer',ARRAY['마녀보감','Secret Healer']::text[],2016,'JTBC',ARRAY['Drama']::text[],'published'),
('볼트론: 전설 속의 수호자','Voltron: Legendary Defender',ARRAY['볼트론: 전설 속의 수호자','Voltron: Legendary Defender','볼트론:전설속의수호자']::text[],2016,'Netflix',ARRAY['Drama']::text[],'published'),
('용팔이','Yong-pal',ARRAY['용팔이','Yong-pal']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('옥탑방 왕세자','Rooftop Prince',ARRAY['옥탑방 왕세자','Rooftop Prince','옥탑방왕세자']::text[],2012,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('로보카폴리','Robocar Poli',ARRAY['로보카폴리','Robocar Poli']::text[],2011,'EBS 1TV',ARRAY['Drama']::text[],'published'),
('성균관 스캔들','Sungkyunkwan Scandal',ARRAY['성균관 스캔들','Sungkyunkwan Scandal','성균관스캔들']::text[],2010,'KBS2',ARRAY['사극','로맨스']::text[],'published'),
('해신','Emperor of the Sea',ARRAY['해신','Emperor of the Sea']::text[],2004,'KBS2',ARRAY['Drama']::text[],'published'),
('천국의 계단','Stairway to Heaven',ARRAY['천국의 계단','Stairway to Heaven','천국의계단']::text[],2003,'SBS',ARRAY['Drama']::text[],'published'),
('가을동화','Autumn in My Heart',ARRAY['가을동화','Autumn in My Heart']::text[],2000,'KBS2',ARRAY['로맨스']::text[],'published'),
('허준','Hur Jun',ARRAY['허준','Hur Jun']::text[],1999,'MBC',ARRAY['Drama']::text[],'published'),
('참교육','Teach You a Lesson',ARRAY['참교육','Teach You a Lesson']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('빅마우스','Big Mouth',ARRAY['빅마우스','Big Mouth']::text[],2022,'MBC',ARRAY['Drama']::text[],'published'),
('청춘기록','Record of Youth',ARRAY['청춘기록','Record of Youth']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('구미호뎐','Tale of the Nine Tailed',ARRAY['구미호뎐','Tale of the Nine Tailed']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('경이로운 소문','The Uncanny Counter',ARRAY['경이로운 소문','The Uncanny Counter','경이로운소문']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('백일의 낭군님','100 Days My Prince',ARRAY['백일의 낭군님','100 Days My Prince','백일의낭군님']::text[],2018,'TVN (Southeast Asia)',ARRAY['Drama']::text[],'published'),
('밥 잘 사주는 예쁜 누나','Something in the Rain',ARRAY['밥 잘 사주는 예쁜 누나','Something in the Rain','밥잘사주는예쁜누나']::text[],2018,'JTBC',ARRAY['로맨스']::text[],'published'),
('시카고 타자기','Chicago Typewriter',ARRAY['시카고 타자기','Chicago Typewriter','시카고타자기']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('레인보우 루비','Rainbow Ruby',ARRAY['레인보우 루비','Rainbow Ruby','레인보우루비']::text[],2016,'EBS 1TV',ARRAY['Drama']::text[],'published'),
('쇼핑왕 루이','Shopaholic Louis',ARRAY['쇼핑왕 루이','Shopaholic Louis','쇼핑왕루이']::text[],2016,'MBC',ARRAY['Drama']::text[],'published'),
('감각남녀','A Girl Who Sees Smells',ARRAY['감각남녀','A Girl Who Sees Smells']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('육룡이 나르샤','Six Flying Dragons',ARRAY['육룡이 나르샤','Six Flying Dragons','육룡이나르샤']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('아랑사또전','Arang and the Magistrate',ARRAY['아랑사또전','Arang and the Magistrate']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('보고싶다','Missing You',ARRAY['보고싶다','Missing You']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('세상 어디에도 없는 착한남자','The Innocent Man',ARRAY['세상 어디에도 없는 착한남자','The Innocent Man','세상어디에도없는착한남자']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('제빵왕 김탁구','Bread, Love and Dreams',ARRAY['제빵왕 김탁구','Bread, Love and Dreams','제빵왕김탁구']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('엄마친구아들','Love Next Door',ARRAY['엄마친구아들','Love Next Door']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('기생수: 더 그레이','Parasyte: The Grey',ARRAY['기생수: 더 그레이','Parasyte: The Grey','기생수:더그레이']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('이재, 곧 죽습니다','Death''s Game',ARRAY['이재, 곧 죽습니다','Death''s Game','이재,곧죽습니다']::text[],2023,'TVING',ARRAY['Drama']::text[],'published'),
('킹더랜드','King the Land',ARRAY['킹더랜드','King the Land']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('마이데몬','My Demon',ARRAY['마이데몬','My Demon']::text[],2023,'SBS',ARRAY['Drama']::text[],'published'),
('기상청 사람들: 사내연애 잔혹사 편','Forecasting Love and Weather',ARRAY['기상청 사람들: 사내연애 잔혹사 편','Forecasting Love and Weather','기상청사람들:사내연애잔혹사편']::text[],2022,'JTBC',ARRAY['Drama']::text[],'published'),
('작은 아씨들','Little Women',ARRAY['작은 아씨들','Little Women','작은아씨들']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('슈룹','Under the Queen''s Umbrella',ARRAY['슈룹','Under the Queen''s Umbrella']::text[],2022,'tvN',ARRAY['사극','코미디']::text[],'published'),
('고스트포스','GhostForce',ARRAY['고스트포스','GhostForce']::text[],2021,'Disney Channel',ARRAY['Drama']::text[],'published'),
('해피니스','Happiness',ARRAY['해피니스','Happiness']::text[],2021,'tvN',ARRAY['스릴러']::text[],'published'),
('그 해 우리는','Our Beloved Summer',ARRAY['그 해 우리는','Our Beloved Summer','그해우리는']::text[],2021,'Netflix',ARRAY['로맨스']::text[],'published'),
('연모','The King''s Affection',ARRAY['연모','The King''s Affection']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('고요의 바다','The Silent Sea',ARRAY['고요의 바다','The Silent Sea','고요의바다']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('그녀의 사생활','Her Private Life',ARRAY['그녀의 사생활','Her Private Life','그녀의사생활']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('날 녹여주오','Melting Me Softly',ARRAY['날 녹여주오','Melting Me Softly','날녹여주오']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('초면에 사랑합니다','The Secret Life of My Secretary',ARRAY['초면에 사랑합니다','The Secret Life of My Secretary','초면에사랑합니다']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('이번 생은 처음이라','Because This is My First Life',ARRAY['이번 생은 처음이라','Because This is My First Life','이번생은처음이라']::text[],2017,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('쌈 마이웨이','Fight for My Way',ARRAY['쌈 마이웨이','Fight for My Way','쌈마이웨이']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('싸우자 귀신아','Hey Ghost, Let''s Fight',ARRAY['싸우자 귀신아','Hey Ghost, Let''s Fight','싸우자귀신아']::text[],2016,'tvN',ARRAY['Drama']::text[],'published'),
('오 마이 비너스','Oh My Venus',ARRAY['오 마이 비너스','Oh My Venus','오마이비너스']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('오렌지 마멀레이드','Orange Marmalade',ARRAY['오렌지 마멀레이드','Orange Marmalade','오렌지마멀레이드']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('이웃집 꽃미남','Flower Boys Next Door',ARRAY['이웃집 꽃미남','Flower Boys Next Door','이웃집꽃미남']::text[],2013,'tvN',ARRAY['Drama']::text[],'published'),
('구가의 서','Gu Family Book',ARRAY['구가의 서','Gu Family Book','구가의서']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('신의','Faith',ARRAY['신의','Faith']::text[],2012,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('응답하라 1997','Reply 1997',ARRAY['응답하라 1997','Reply 1997','응답하라1997']::text[],2012,'tvN',ARRAY['로맨스','가족']::text[],'published'),
('학교 2013','School 2013',ARRAY['학교 2013','School 2013','학교2013']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('보스를 지켜라','Protect the Boss',ARRAY['보스를 지켜라','Protect the Boss','보스를지켜라']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('꼬마버스 타요','Tayo the Little Bus',ARRAY['꼬마버스 타요','Tayo the Little Bus','꼬마버스타요']::text[],2010,'Korea Educational Broadcasting System',ARRAY['Drama']::text[],'published'),
('미안하다, 사랑한다','I''m Sorry, I Love You',ARRAY['미안하다, 사랑한다','I''m Sorry, I Love You','미안하다,사랑한다']::text[],2004,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('이 사랑 통역 되나요?','Can This Love Be Translated?',ARRAY['이 사랑 통역 되나요?','Can This Love Be Translated?','이사랑통역되나요?']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('경성크리처','Gyeongseong Creature',ARRAY['경성크리처','Gyeongseong Creature']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('파친코','Pachinko',ARRAY['파친코','Pachinko']::text[],2022,'Apple',ARRAY['가족','시대극']::text[],'published'),
('배가본드','Vagabond',ARRAY['배가본드','Vagabond']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('동백꽃 필 무렵','When the Camellia Blooms',ARRAY['동백꽃 필 무렵','When the Camellia Blooms','동백꽃필무렵']::text[],2019,'KBS2',ARRAY['로맨스','코미디']::text[],'published'),
('사임당, the Herstory','Saimdang, Memoir of Colors',ARRAY['사임당, the Herstory','Saimdang, Memoir of Colors','사임당,theHerstory']::text[],2017,'SBS',ARRAY['Drama']::text[],'published'),
('학교 2017','School 2017',ARRAY['학교 2017','School 2017','학교2017']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('신데렐라와 네 명의 기사','Cinderella with Four Knights',ARRAY['신데렐라와 네 명의 기사','Cinderella with Four Knights','신데렐라와네명의기사']::text[],2016,'tvN',ARRAY['Drama']::text[],'published'),
('블러드','Blood',ARRAY['블러드','Blood']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('닥터 이방인','Doctor Stranger',ARRAY['닥터 이방인','Doctor Stranger','닥터이방인']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('응급남녀','Emergency Man and Woman',ARRAY['응급남녀','Emergency Man and Woman']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('미생 - 아직 살아 있지 못한 자','Misaeng',ARRAY['미생 - 아직 살아 있지 못한 자','Misaeng','미생-아직살아있지못한자']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('잭과 팡','Zack & Quack',ARRAY['잭과 팡','Zack & Quack','잭과팡']::text[],2014,'Nick Jr. Channel',ARRAY['Drama']::text[],'published'),
('사랑비','Love Rain',ARRAY['사랑비','Love Rain']::text[],2012,'KBS2',ARRAY['Drama']::text[],'published'),
('쇼 챔피언','Show Champion',ARRAY['쇼 챔피언','Show Champion','쇼챔피언']::text[],2012,'MBC Music',ARRAY['Drama']::text[],'published'),
('아름다운 그대에게','To the Beautiful You',ARRAY['아름다운 그대에게','To the Beautiful You','아름다운그대에게']::text[],2012,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('49일','49 Days',ARRAY['49일','49 Days']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('마이 프린세스','My Princess',ARRAY['마이 프린세스','My Princess','마이프린세스']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('신데렐라 언니','Cinderella''s Sister',ARRAY['신데렐라 언니','Cinderella''s Sister','신데렐라언니']::text[],2010,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('파스타','Pasta',ARRAY['파스타','Pasta']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('일지매','Iljimae',ARRAY['일지매','Iljimae']::text[],2008,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('바람의 화원','Painter of the Wind',ARRAY['바람의 화원','Painter of the Wind','바람의화원']::text[],2008,'SBS',ARRAY['Drama']::text[],'published'),
('이산','Lee San, Wind of the Palace',ARRAY['이산','Lee San, Wind of the Palace']::text[],2007,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('태왕사신기','The Legend',ARRAY['태왕사신기','The Legend']::text[],2007,'MBC',ARRAY['Drama']::text[],'published'),
('기리고','If Wishes Could Kill',ARRAY['기리고','If Wishes Could Kill']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('중증외상센터','The Trauma Code: Heroes on Call',ARRAY['중증외상센터','The Trauma Code: Heroes on Call']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('닥터 슬럼프','Doctor Slump',ARRAY['닥터 슬럼프','Doctor Slump','닥터슬럼프']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('선재 업고 튀어','Lovely Runner',ARRAY['선재 업고 튀어','Lovely Runner','선재업고튀어']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('사냥개들','Bloodhounds',ARRAY['사냥개들','Bloodhounds']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('일타 스캔들','Crash Course in Romance',ARRAY['일타 스캔들','Crash Course in Romance','일타스캔들']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('반짝이는 워터멜론','Twinkling Watermelon',ARRAY['반짝이는 워터멜론','Twinkling Watermelon','반짝이는워터멜론']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('소년심판','Juvenile Justice',ARRAY['소년심판','Juvenile Justice']::text[],2022,'Netflix',ARRAY['법률','드라마']::text[],'published'),
('재벌집 막내아들','Reborn Rich',ARRAY['재벌집 막내아들','Reborn Rich','재벌집막내아들']::text[],2022,'JTBC',ARRAY['드라마','판타지']::text[],'published'),
('약한영웅 Class 1','Weak Hero Class 1',ARRAY['약한영웅 Class 1','Weak Hero Class 1','약한영웅Class1']::text[],2022,'Netflix',ARRAY['액션','청춘']::text[],'published'),
('마우스','Mouse',ARRAY['마우스','Mouse']::text[],2021,'tvN',ARRAY['스릴러']::text[],'published'),
('악마판사','The Devil Judge',ARRAY['악마판사','The Devil Judge']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('아스달 연대기','Arthdal Chronicles',ARRAY['아스달 연대기','Arthdal Chronicles','아스달연대기']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('타인은 지옥이다','Hell Is Other People',ARRAY['타인은 지옥이다','Hell Is Other People','타인은지옥이다']::text[],2019,'OCN',ARRAY['Drama']::text[],'published'),
('좋아하면 울리는','Love Alarm',ARRAY['좋아하면 울리는','Love Alarm','좋아하면울리는']::text[],2019,'Netflix',ARRAY['Drama']::text[],'published'),
('로맨스는 별책부록','Romance Is a Bonus Book',ARRAY['로맨스는 별책부록','Romance Is a Bonus Book','로맨스는별책부록']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('조선로코 녹두전','The Tale of Nokdu',ARRAY['조선로코 녹두전','The Tale of Nokdu','조선로코녹두전']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('알함브라 궁전의 추억','Memories of the Alhambra',ARRAY['알함브라 궁전의 추억','Memories of the Alhambra','알함브라궁전의추억']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('라디오 로맨스','Radio Romance',ARRAY['라디오 로맨스','Radio Romance','라디오로맨스']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('으라차차 와이키키','Welcome to Waikiki',ARRAY['으라차차 와이키키','Welcome to Waikiki','으라차차와이키키']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);