INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('블랙','Black',ARRAY['블랙','Black']::text[],2017,'OCN',ARRAY['Drama']::text[],'published'),
('7일의 왕비','Queen for Seven Days',ARRAY['7일의 왕비','Queen for Seven Days','7일의왕비']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('비밀의 숲','Stranger',ARRAY['비밀의 숲','Stranger','비밀의숲']::text[],2017,'tvN',ARRAY['스릴러','법률']::text[],'published'),
('내일 그대와','Tomorrow With You',ARRAY['내일 그대와','Tomorrow With You','내일그대와']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('치즈인더트랩','Cheese in the Trap',ARRAY['치즈인더트랩','Cheese in the Trap']::text[],2016,'tvN',ARRAY['로맨스']::text[],'published'),
('몰랑이','Molang',ARRAY['몰랑이','Molang']::text[],2016,'Disney Jr.',ARRAY['Drama']::text[],'published'),
('너를 기억해','Hello Monster',ARRAY['너를 기억해','Hello Monster','너를기억해']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('밤을 걷는 선비','Scholar Who Walks the Night',ARRAY['밤을 걷는 선비','Scholar Who Walks the Night','밤을걷는선비']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('퐁당퐁당 Love','Splash Splash Love',ARRAY['퐁당퐁당 Love','Splash Splash Love','퐁당퐁당Love']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('맨도롱 또똣','Warm and Cozy',ARRAY['맨도롱 또똣','Warm and Cozy','맨도롱또똣']::text[],2015,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내겐 너무 사랑스러운 그녀','My Lovely Girl',ARRAY['내겐 너무 사랑스러운 그녀','My Lovely Girl','내겐너무사랑스러운그녀']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('야경꾼 일지','Night Watchman''s Journal',ARRAY['야경꾼 일지','Night Watchman''s Journal','야경꾼일지']::text[],2014,'MBC',ARRAY['Drama']::text[],'published'),
('예쁜 남자','Bel Ami',ARRAY['예쁜 남자','Bel Ami','예쁜남자']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('불의 여신 정이','Goddess of Fire',ARRAY['불의 여신 정이','Goddess of Fire','불의여신정이']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('응답하라 1994','Reply 1994',ARRAY['응답하라 1994','Reply 1994','응답하라1994']::text[],2013,'tvN',ARRAY['로맨스','청춘']::text[],'published'),
('그 겨울, 바람이 분다','That Winter, The Wind Blows',ARRAY['그 겨울, 바람이 분다','That Winter, The Wind Blows','그겨울,바람이분다']::text[],2013,'Seoul Broadcasting System',ARRAY['로맨스']::text[],'published'),
('신사의 품격','A Gentleman''s Dignity',ARRAY['신사의 품격','A Gentleman''s Dignity','신사의품격']::text[],2012,'Seoul Broadcasting System',ARRAY['로맨스','코미디']::text[],'published'),
('빅','Big',ARRAY['빅','Big']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('인현왕후의 남자','Queen In-Hyun''s Man',ARRAY['인현왕후의 남자','Queen In-Hyun''s Man','인현왕후의남자']::text[],2012,'tvN',ARRAY['Drama']::text[],'published'),
('최고의 사랑','The Greatest Love',ARRAY['최고의 사랑','The Greatest Love','최고의사랑']::text[],2011,'MBC',ARRAY['Drama']::text[],'published'),
('추노','Chuno',ARRAY['추노','Chuno']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('찬란한 유산','Brilliant Legacy',ARRAY['찬란한 유산','Brilliant Legacy','찬란한유산']::text[],2009,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('다모','Damo',ARRAY['다모','Damo']::text[],2003,'MBC',ARRAY['Drama']::text[],'published'),
('여름향기','Summer Scent',ARRAY['여름향기','Summer Scent']::text[],2003,'KBS2',ARRAY['Drama']::text[],'published'),
('상도','The Merchant of Joseon',ARRAY['상도','The Merchant of Joseon']::text[],2001,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('폭군의 셰프','Bon Appétit, Your Majesty',ARRAY['폭군의 셰프','Bon Appétit, Your Majesty','폭군의셰프']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('다 이루어질지니','Genie, Make a Wish',ARRAY['다 이루어질지니','Genie, Make a Wish','다이루어질지니']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('굿보이','Good Boy',ARRAY['굿보이','Good Boy']::text[],2025,'JTBC',ARRAY['Drama']::text[],'published'),
('별들에게 물어봐','When the Stars Gossip',ARRAY['별들에게 물어봐','When the Stars Gossip','별들에게물어봐']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('더 에이트 쇼','The 8 Show',ARRAY['더 에이트 쇼','The 8 Show','더에이트쇼']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('힙(HIP)하게','Behind your Touch',ARRAY['힙(HIP)하게','Behind your Touch']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('정신병동에도 아침이 와요','Daily Dose of Sunshine',ARRAY['정신병동에도 아침이 와요','Daily Dose of Sunshine','정신병동에도아침이와요']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이두나!','Doona!',ARRAY['이두나!','Doona!']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이번 생도 잘 부탁해','See You in My 19th Life',ARRAY['이번 생도 잘 부탁해','See You in My 19th Life','이번생도잘부탁해']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('웰컴투 삼달리','Welcome to Samdalri',ARRAY['웰컴투 삼달리','Welcome to Samdalri','웰컴투삼달리']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('어게인 마이 라이프','Again My Life',ARRAY['어게인 마이 라이프','Again My Life','어게인마이라이프']::text[],2022,'SBS',ARRAY['Drama']::text[],'published'),
('고스트 닥터','Ghost Doctor',ARRAY['고스트 닥터','Ghost Doctor','고스트닥터']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('무브 투 헤븐: 나는 유품정리사입니다','Move to Heaven',ARRAY['무브 투 헤븐: 나는 유품정리사입니다','Move to Heaven','무브투헤븐:나는유품정리사입니다']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('나빌레라','Navillera',ARRAY['나빌레라','Navillera']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('알고있지만','Nevertheless',ARRAY['알고있지만','Nevertheless']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('아기상어 올리와 윌리엄','Baby Shark''s Big Show!',ARRAY['아기상어 올리와 윌리엄','Baby Shark''s Big Show!','아기상어올리와윌리엄']::text[],2020,'Nickelodeon',ARRAY['Drama']::text[],'published'),
('편의점 샛별이','Backstreet Rookie',ARRAY['편의점 샛별이','Backstreet Rookie','편의점샛별이']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('도도솔솔라라솔','Do Do Sol Sol La La Sol',ARRAY['도도솔솔라라솔','Do Do Sol Sol La La Sol']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('인간수업','Extracurricular',ARRAY['인간수업','Extracurricular']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('나 홀로 그대','My Holo Love',ARRAY['나 홀로 그대','My Holo Love','나홀로그대']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('쌍갑포차','Mystic Pop-up Bar',ARRAY['쌍갑포차','Mystic Pop-up Bar']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('날씨가 좋으면 찾아가겠어요','When the Weather Is Fine',ARRAY['날씨가 좋으면 찾아가겠어요','When the Weather Is Fine','날씨가좋으면찾아가겠어요']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('어비스','Abyss',ARRAY['어비스','Abyss']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('우아한 가','Graceful Family',ARRAY['우아한 가','Graceful Family','우아한가']::text[],2019,'Maeil Broadcasting Network',ARRAY['Drama']::text[],'published'),
('검색어를 입력하세요: www','Search: WWW',ARRAY['검색어를 입력하세요: www','Search: WWW','검색어를입력하세요:www']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('열혈사제','The Fiery Priest',ARRAY['열혈사제','The Fiery Priest']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('무법 변호사','Lawless Lawyer',ARRAY['무법 변호사','Lawless Lawyer','무법변호사']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('나의 아저씨','My Mister',ARRAY['나의 아저씨','My Mister','나의아저씨']::text[],2018,'tvN',ARRAY['드라마']::text[],'published'),
('내 뒤에 테리우스','My Secret Terrius',ARRAY['내 뒤에 테리우스','My Secret Terrius','내뒤에테리우스']::text[],2018,'MBC',ARRAY['Drama']::text[],'published'),
('서른이지만 열일곱입니다','Still 17',ARRAY['서른이지만 열일곱입니다','Still 17','서른이지만열일곱입니다']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('슈츠','Suits',ARRAY['슈츠','Suits']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('황후의 품격','The Last Empress',ARRAY['황후의 품격','The Last Empress','황후의품격']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('여우각시별','Where Stars Land',ARRAY['여우각시별','Where Stars Land']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('사랑의 온도','Temperature of Love',ARRAY['사랑의 온도','Temperature of Love','사랑의온도']::text[],2017,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('하백의 신부 2017','The Bride of Habaek',ARRAY['하백의 신부 2017','The Bride of Habaek','하백의신부2017']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('보이스','Voice',ARRAY['보이스','Voice']::text[],2017,'OCN',ARRAY['스릴러']::text[],'published'),
('또 오해영','Another Miss Oh',ARRAY['또 오해영','Another Miss Oh','또오해영']::text[],2016,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('무림학교','Moorim School',ARRAY['무림학교','Moorim School']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('우리 옆집에 EXO가 산다','EXO Next Door',ARRAY['우리 옆집에 EXO가 산다','EXO Next Door','우리옆집에EXO가산다']::text[],2015,'JTBC2',ARRAY['Drama']::text[],'published'),
('하이드 지킬, 나','Jekyll and Me',ARRAY['하이드 지킬, 나','Jekyll and Me','하이드지킬,나']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('가면','Mask',ARRAY['가면','Mask']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('리멤버 - 아들의 전쟁','Remember: War of the Son',ARRAY['리멤버 - 아들의 전쟁','Remember: War of the Son','리멤버-아들의전쟁']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('조선 총잡이','Gunman in Joseon',ARRAY['조선 총잡이','Gunman in Joseon','조선총잡이']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('하이스쿨 러브온','Hi! School: Love On',ARRAY['하이스쿨 러브온','Hi! School: Love On','하이스쿨러브온']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('괜찮아, 사랑이야','It''s Okay, That''s Love',ARRAY['괜찮아, 사랑이야','It''s Okay, That''s Love','괜찮아,사랑이야']::text[],2014,'SBS',ARRAY['Drama']::text[],'published'),
('가족끼리 왜 이래','What Happens to My Family?',ARRAY['가족끼리 왜 이래','What Happens to My Family?','가족끼리왜이래']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('더킹2Hearts','The King 2 Hearts',ARRAY['더킹2Hearts','The King 2 Hearts']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('마의','The King''s Doctor',ARRAY['마의','The King''s Doctor']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내게 거짓말을 해봐','Lie to Me',ARRAY['내게 거짓말을 해봐','Lie to Me','내게거짓말을해봐']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('공주의 남자','The Princess'' Man',ARRAY['공주의 남자','The Princess'' Man','공주의남자']::text[],2011,'KBS2',ARRAY['Drama']::text[],'published'),
('대물','Big Thing',ARRAY['대물','Big Thing']::text[],2010,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('매리는 외박중','Mary Stayed Out All Night',ARRAY['매리는 외박중','Mary Stayed Out All Night','매리는외박중']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('황진이','Hwang Jini',ARRAY['황진이','Hwang Jini']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('봄의 왈츠','Spring Waltz',ARRAY['봄의 왈츠','Spring Waltz','봄의왈츠']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('킬러들의 쇼핑몰','A Shop for Killers',ARRAY['킬러들의 쇼핑몰','A Shop for Killers','킬러들의쇼핑몰']::text[],2024,'Star',ARRAY['Drama']::text[],'published'),
('낮과 밤이 다른 그녀','Miss Night and Day',ARRAY['낮과 밤이 다른 그녀','Miss Night and Day','낮과밤이다른그녀']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('피라미드 게임','Pyramid Game',ARRAY['피라미드 게임','Pyramid Game','피라미드게임']::text[],2024,'TVING',ARRAY['Drama']::text[],'published'),
('히어로는 아닙니다만','The Atypical Family',ARRAY['히어로는 아닙니다만','The Atypical Family','히어로는아닙니다만']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('너의 시간 속으로','A Time Called You',ARRAY['너의 시간 속으로','A Time Called You','너의시간속으로']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('택배기사','Black Knight',ARRAY['택배기사','Black Knight']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('셀러브리티','Celebrity',ARRAY['셀러브리티','Celebrity']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이 연애는 불가항력','Destined With You',ARRAY['이 연애는 불가항력','Destined With You','이연애는불가항력']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('연애대전','Love to Hate You',ARRAY['연애대전','Love to Hate You']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('마스크걸','Mask Girl',ARRAY['마스크걸','Mask Girl']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('천원짜리 변호사','One Dollar Lawyer',ARRAY['천원짜리 변호사','One Dollar Lawyer','천원짜리변호사']::text[],2022,'SBS',ARRAY['Drama']::text[],'published'),
('우리들의 블루스','Our Blues',ARRAY['우리들의 블루스','Our Blues','우리들의블루스']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('썸바디','Somebody',ARRAY['썸바디','Somebody']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('안나라수마나라','The Sound of Magic',ARRAY['안나라수마나라','The Sound of Magic']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('간 떨어지는 동거','My Roommate is a Gumiho',ARRAY['간 떨어지는 동거','My Roommate is a Gumiho','간떨어지는동거']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('원 더 우먼','One the Woman',ARRAY['원 더 우먼','One the Woman','원더우먼']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('대박부동산','Sell Your Haunted House',ARRAY['대박부동산','Sell Your Haunted House']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('오월의 청춘','Youth of May',ARRAY['오월의 청춘','Youth of May','오월의청춘']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('앨리스','Alice',ARRAY['앨리스','Alice']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('그 남자의 기억법','Find Me in Your Memory',ARRAY['그 남자의 기억법','Find Me in Your Memory','그남자의기억법']::text[],2020,'MBC',ARRAY['Drama']::text[],'published'),
('키포와 신기한 동물들','Kipo and the Age of Wonderbeasts',ARRAY['키포와 신기한 동물들','Kipo and the Age of Wonderbeasts','키포와신기한동물들']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('어서와','Welcome',ARRAY['어서와','Welcome']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('닥터 프리즈너','Doctor Prisoner',ARRAY['닥터 프리즈너','Doctor Prisoner','닥터프리즈너']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('열여덟의 순간','The Moment of 18',ARRAY['열여덟의 순간','The Moment of 18','열여덟의순간']::text[],2019,'JTBC',ARRAY['Drama']::text[],'published'),
('사의 찬미','The Hymn of Death',ARRAY['사의 찬미','The Hymn of Death','사의찬미']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('크리미널 마인드','Criminal Minds',ARRAY['크리미널 마인드','Criminal Minds','크리미널마인드']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('최고의 한방','Hit the Top',ARRAY['최고의 한방','Hit the Top','최고의한방']::text[],2017,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('그녀는 거짓말을 너무 사랑해','The Liar and His Lover',ARRAY['그녀는 거짓말을 너무 사랑해','The Liar and His Lover','그녀는거짓말을너무사랑해']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('돌아와요 아저씨','Come Back Mister',ARRAY['돌아와요 아저씨','Come Back Mister','돌아와요아저씨']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('사랑하는 은동아','Beloved Eun-dong',ARRAY['사랑하는 은동아','Beloved Eun-dong','사랑하는은동아']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('순정에 반하다','Falling for Innocence',ARRAY['순정에 반하다','Falling for Innocence','순정에반하다']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('상류사회','High Society',ARRAY['상류사회','High Society']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('하녀들','Maids',ARRAY['하녀들','Maids']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('두번째 스무살','Second 20s',ARRAY['두번째 스무살','Second 20s','두번째스무살']::text[],2015,'tvN',ARRAY['Drama']::text[],'published'),
('트라이앵글','Triangle',ARRAY['트라이앵글','Triangle']::text[],2014,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('7급 공무원','7th Grade Civil Servant',ARRAY['7급 공무원','7th Grade Civil Servant','7급공무원']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('야왕','Queen of Ambition',ARRAY['야왕','Queen of Ambition']::text[],2013,'SBS',ARRAY['Drama']::text[],'published'),
('투웍스','Two Weeks',ARRAY['투웍스','Two Weeks']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('천일의 약속','A Thousand Days'' Promise',ARRAY['천일의 약속','A Thousand Days'' Promise','천일의약속']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('꽃미남 라면가게','Flower Boy Ramen Shop',ARRAY['꽃미남 라면가게','Flower Boy Ramen Shop','꽃미남라면가게']::text[],2011,'tvN',ARRAY['Drama']::text[],'published'),
('영광의 재인','Glory Jane',ARRAY['영광의 재인','Glory Jane','영광의재인']::text[],2011,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('계백','Gyebaek',ARRAY['계백','Gyebaek']::text[],2011,'MBC',ARRAY['Drama']::text[],'published'),
('주간 아이돌','Weekly Idol',ARRAY['주간 아이돌','Weekly Idol','주간아이돌']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('아테나: 전쟁의 여신','Athena: Goddess of War',ARRAY['아테나: 전쟁의 여신','Athena: Goddess of War','아테나:전쟁의여신']::text[],2010,'SBS',ARRAY['Drama']::text[],'published'),
('아가씨를 부탁해','My Fair Lady',ARRAY['아가씨를 부탁해','My Fair Lady','아가씨를부탁해']::text[],2009,'KBS2',ARRAY['Drama']::text[],'published'),
('에덴의 동쪽','East of Eden',ARRAY['에덴의 동쪽','East of Eden','에덴의동쪽']::text[],2008,'MBC',ARRAY['Drama']::text[],'published'),
('우리 결혼했어요','We Got Married',ARRAY['우리 결혼했어요','We Got Married','우리결혼했어요']::text[],2008,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('왕과 나','The King and I',ARRAY['왕과 나','The King and I','왕과나']::text[],2007,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('개와 늑대의 시간','Time Between Dog and Wolf',ARRAY['개와 늑대의 시간','Time Between Dog and Wolf','개와늑대의시간']::text[],2007,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('환상의 커플','Couple or Trouble',ARRAY['환상의 커플','Couple or Trouble','환상의커플']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('별은 내 가슴에','Star in My Heart',ARRAY['별은 내 가슴에','Star in My Heart','별은내가슴에']::text[],1997,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('첫사랑','First Love',ARRAY['첫사랑','First Love']::text[],1996,'KBS2',ARRAY['Drama']::text[],'published'),
('여명의 눈동자','Eyes of Dawn',ARRAY['여명의 눈동자','Eyes of Dawn','여명의눈동자']::text[],1991,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('21세기 대군부인','Perfect Crown',ARRAY['21세기 대군부인','Perfect Crown','21세기대군부인']::text[],2026,'MBC',ARRAY['Drama']::text[],'published'),
('동궁','The East Palace',ARRAY['동궁','The East Palace']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('에스콰이어: 변호사를 꿈꾸는 변호사들','Beyond the Bar',ARRAY['에스콰이어: 변호사를 꿈꾸는 변호사들','Beyond the Bar','에스콰이어:변호사를꿈꾸는변호사들']::text[],2025,'JTBC',ARRAY['Drama']::text[],'published'),
('탄금','Dear Hongrang',ARRAY['탄금','Dear Hongrang']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('선의의 경쟁','Friendly Rivalry',ARRAY['선의의 경쟁','Friendly Rivalry','선의의경쟁']::text[],2025,'U+Mobile',ARRAY['Drama']::text[],'published'),
('스터디그룹','Study Group',ARRAY['스터디그룹','Study Group']::text[],2025,'TVING',ARRAY['Drama']::text[],'published'),
('자백의 대가','The Price of Confession',ARRAY['자백의 대가','The Price of Confession','자백의대가']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('살인자ㅇ난감','A Killer Paradox',ARRAY['살인자ㅇ난감','A Killer Paradox']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('닭강정','Chicken Nugget',ARRAY['닭강정','Chicken Nugget']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('조립식 가족','Family by Choice',ARRAY['조립식 가족','Family by Choice','조립식가족']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('재벌X형사','Flex X Cop',ARRAY['재벌X형사','Flex X Cop']::text[],2024,'SBS',ARRAY['Drama']::text[],'published'),
('종말의 바보','Goodbye Earth',ARRAY['종말의 바보','Goodbye Earth','종말의바보']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('아무도 없는 숲속에서','The Frog',ARRAY['아무도 없는 숲속에서','The Frog','아무도없는숲속에서']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('지금 거신 전화는','When the Phone Rings',ARRAY['지금 거신 전화는','When the Phone Rings','지금거신전화는']::text[],2024,'MBC',ARRAY['Drama']::text[],'published'),
('딜리버리 맨!','Delivery Man',ARRAY['딜리버리 맨!','Delivery Man','딜리버리맨!']::text[],2023,'Genie',ARRAY['Drama']::text[],'published'),
('무빙','Moving',ARRAY['무빙','Moving']::text[],2023,'Hulu',ARRAY['액션','판타지']::text[],'published'),
('슈퍼맨과 나의 모험','My Adventures with Superman',ARRAY['슈퍼맨과 나의 모험','My Adventures with Superman','슈퍼맨과나의모험']::text[],2023,'Adult Swim',ARRAY['Drama']::text[],'published'),
('연인','My Dearest',ARRAY['연인','My Dearest']::text[],2023,'MBC',ARRAY['Drama']::text[],'published'),
('퀸메이커','Queenmaker',ARRAY['퀸메이커','Queenmaker']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('힘쎈여자 강남순','Strong Girl Nam-soon',ARRAY['힘쎈여자 강남순','Strong Girl Nam-soon','힘쎈여자강남순']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('붉은 단심','Bloody Heart',ARRAY['붉은 단심','Bloody Heart','붉은단심']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('미남당','Café Minamdang',ARRAY['미남당','Café Minamdang']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('커넥트','Connect',ARRAY['커넥트','Connect']::text[],2022,'Hulu',ARRAY['Drama']::text[],'published'),
('월수금화목토','Love in Contract',ARRAY['월수금화목토','Love in Contract']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('군검사 도베르만','Military Prosecutor Doberman',ARRAY['군검사 도베르만','Military Prosecutor Doberman','군검사도베르만']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('어쩌다 전원일기','Once Upon a Small Town',ARRAY['어쩌다 전원일기','Once Upon a Small Town','어쩌다전원일기']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('조선 정신과 의사 유세풍','Poong, the Joseon Psychiatrist',ARRAY['조선 정신과 의사 유세풍','Poong, the Joseon Psychiatrist','조선정신과의사유세풍']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('3인칭 복수','Revenge of Others',ARRAY['3인칭 복수','Revenge of Others','3인칭복수']::text[],2022,'Star',ARRAY['Drama']::text[],'published'),
('사운드트랙 #1','Soundtrack #1',ARRAY['사운드트랙 #1','Soundtrack #1','사운드트랙#1']::text[],2022,'Star',ARRAY['Drama']::text[],'published'),
('금수저','The Golden Spoon',ARRAY['금수저','The Golden Spoon']::text[],2022,'MBC',ARRAY['Drama']::text[],'published'),
('괴물','Beyond Evil',ARRAY['괴물','Beyond Evil']::text[],2021,'JTBC',ARRAY['스릴러','범죄']::text[],'published'),
('달리와 감자탕','Dali and Cocky Prince',ARRAY['달리와 감자탕','Dali and Cocky Prince','달리와감자탕']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('홍천기','Lovers of the Red Sky',ARRAY['홍천기','Lovers of the Red Sky']::text[],2021,'SBS',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);