INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('그녀의 사생활','Her Private Life',ARRAY['그녀의 사생활','Her Private Life','그녀의사생활']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('날 녹여주오','Melting Me Softly',ARRAY['날 녹여주오','Melting Me Softly','날녹여주오']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('초면에 사랑합니다','The Secret Life of My Secretary',ARRAY['초면에 사랑합니다','The Secret Life of My Secretary','초면에사랑합니다']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('이번 생은 처음이라','Because This is My First Life',ARRAY['이번 생은 처음이라','Because This is My First Life','이번생은처음이라']::text[],2017,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('쌈 마이웨이','Fight for My Way',ARRAY['쌈 마이웨이','Fight for My Way','쌈마이웨이']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('싸우자 귀신아','Hey Ghost, Let''s Fight',ARRAY['싸우자 귀신아','Hey Ghost, Let''s Fight','싸우자귀신아']::text[],2016,'tvN',ARRAY['Drama']::text[],'published'),
('오 마이 비너스','Oh My Venus',ARRAY['오 마이 비너스','Oh My Venus','오마이비너스']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('오렌지 마멀레이드','Orange Marmalade',ARRAY['오렌지 마멀레이드','Orange Marmalade','오렌지마멀레이드']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('이웃집 꽃미남','Flower Boys Next Door',ARRAY['이웃집 꽃미남','Flower Boys Next Door','이웃집꽃미남']::text[],2013,'tvN',ARRAY['Drama']::text[],'published'),
('구가의 서','Gu Family Book',ARRAY['구가의 서','Gu Family Book','구가의서']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('신의','Faith',ARRAY['신의','Faith']::text[],2012,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('응답하라 1997','Reply 1997',ARRAY['응답하라 1997','Reply 1997','응답하라1997']::text[],2012,'tvN',ARRAY['로맨스','가족']::text[],'published'),
('학교 2013','School 2013',ARRAY['학교 2013','School 2013','학교2013']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('보스를 지켜라','Protect the Boss',ARRAY['보스를 지켜라','Protect the Boss','보스를지켜라']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('꼬마버스 타요','Tayo the Little Bus',ARRAY['꼬마버스 타요','Tayo the Little Bus','꼬마버스타요']::text[],2010,'Korea Educational Broadcasting System',ARRAY['Drama']::text[],'published'),
('미안하다, 사랑한다','I''m Sorry, I Love You',ARRAY['미안하다, 사랑한다','I''m Sorry, I Love You','미안하다,사랑한다']::text[],2004,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('이 사랑 통역 되나요?','Can This Love Be Translated?',ARRAY['이 사랑 통역 되나요?','Can This Love Be Translated?','이사랑통역되나요?']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('경성크리처','Gyeongseong Creature',ARRAY['경성크리처','Gyeongseong Creature']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('파친코','Pachinko',ARRAY['파친코','Pachinko']::text[],2022,'Apple',ARRAY['가족','시대극']::text[],'published'),
('배가본드','Vagabond',ARRAY['배가본드','Vagabond']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('동백꽃 필 무렵','When the Camellia Blooms',ARRAY['동백꽃 필 무렵','When the Camellia Blooms','동백꽃필무렵']::text[],2019,'KBS2',ARRAY['로맨스','코미디']::text[],'published'),
('사임당, the Herstory','Saimdang, Memoir of Colors',ARRAY['사임당, the Herstory','Saimdang, Memoir of Colors','사임당,theHerstory']::text[],2017,'SBS',ARRAY['Drama']::text[],'published'),
('학교 2017','School 2017',ARRAY['학교 2017','School 2017','학교2017']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('신데렐라와 네 명의 기사','Cinderella with Four Knights',ARRAY['신데렐라와 네 명의 기사','Cinderella with Four Knights','신데렐라와네명의기사']::text[],2016,'tvN',ARRAY['Drama']::text[],'published'),
('블러드','Blood',ARRAY['블러드','Blood']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('닥터 이방인','Doctor Stranger',ARRAY['닥터 이방인','Doctor Stranger','닥터이방인']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('응급남녀','Emergency Man and Woman',ARRAY['응급남녀','Emergency Man and Woman']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('미생 - 아직 살아 있지 못한 자','Misaeng',ARRAY['미생 - 아직 살아 있지 못한 자','Misaeng','미생-아직살아있지못한자']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('잭과 팡','Zack & Quack',ARRAY['잭과 팡','Zack & Quack','잭과팡']::text[],2014,'Nick Jr. Channel',ARRAY['Drama']::text[],'published'),
('사랑비','Love Rain',ARRAY['사랑비','Love Rain']::text[],2012,'KBS2',ARRAY['Drama']::text[],'published'),
('쇼 챔피언','Show Champion',ARRAY['쇼 챔피언','Show Champion','쇼챔피언']::text[],2012,'MBC Music',ARRAY['Drama']::text[],'published'),
('아름다운 그대에게','To the Beautiful You',ARRAY['아름다운 그대에게','To the Beautiful You','아름다운그대에게']::text[],2012,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('49일','49 Days',ARRAY['49일','49 Days']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('마이 프린세스','My Princess',ARRAY['마이 프린세스','My Princess','마이프린세스']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('신데렐라 언니','Cinderella''s Sister',ARRAY['신데렐라 언니','Cinderella''s Sister','신데렐라언니']::text[],2010,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('파스타','Pasta',ARRAY['파스타','Pasta']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('일지매','Iljimae',ARRAY['일지매','Iljimae']::text[],2008,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('바람의 화원','Painter of the Wind',ARRAY['바람의 화원','Painter of the Wind','바람의화원']::text[],2008,'SBS',ARRAY['Drama']::text[],'published'),
('이산','Lee San, Wind of the Palace',ARRAY['이산','Lee San, Wind of the Palace']::text[],2007,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('태왕사신기','The Legend',ARRAY['태왕사신기','The Legend']::text[],2007,'MBC',ARRAY['Drama']::text[],'published'),
('기리고','If Wishes Could Kill',ARRAY['기리고','If Wishes Could Kill']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('중증외상센터','The Trauma Code: Heroes on Call',ARRAY['중증외상센터','The Trauma Code: Heroes on Call']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('닥터 슬럼프','Doctor Slump',ARRAY['닥터 슬럼프','Doctor Slump','닥터슬럼프']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('선재 업고 튀어','Lovely Runner',ARRAY['선재 업고 튀어','Lovely Runner','선재업고튀어']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('사냥개들','Bloodhounds',ARRAY['사냥개들','Bloodhounds']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('일타 스캔들','Crash Course in Romance',ARRAY['일타 스캔들','Crash Course in Romance','일타스캔들']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('반짝이는 워터멜론','Twinkling Watermelon',ARRAY['반짝이는 워터멜론','Twinkling Watermelon','반짝이는워터멜론']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('소년심판','Juvenile Justice',ARRAY['소년심판','Juvenile Justice']::text[],2022,'Netflix',ARRAY['법률','드라마']::text[],'published'),
('재벌집 막내아들','Reborn Rich',ARRAY['재벌집 막내아들','Reborn Rich','재벌집막내아들']::text[],2022,'JTBC',ARRAY['드라마','판타지']::text[],'published'),
('약한영웅 Class 1','Weak Hero Class 1',ARRAY['약한영웅 Class 1','Weak Hero Class 1','약한영웅Class1']::text[],2022,'Netflix',ARRAY['액션','청춘']::text[],'published'),
('마우스','Mouse',ARRAY['마우스','Mouse']::text[],2021,'tvN',ARRAY['스릴러']::text[],'published'),
('악마판사','The Devil Judge',ARRAY['악마판사','The Devil Judge']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('아스달 연대기','Arthdal Chronicles',ARRAY['아스달 연대기','Arthdal Chronicles','아스달연대기']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('타인은 지옥이다','Hell Is Other People',ARRAY['타인은 지옥이다','Hell Is Other People','타인은지옥이다']::text[],2019,'OCN',ARRAY['Drama']::text[],'published'),
('좋아하면 울리는','Love Alarm',ARRAY['좋아하면 울리는','Love Alarm','좋아하면울리는']::text[],2019,'Netflix',ARRAY['Drama']::text[],'published'),
('로맨스는 별책부록','Romance Is a Bonus Book',ARRAY['로맨스는 별책부록','Romance Is a Bonus Book','로맨스는별책부록']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('조선로코 녹두전','The Tale of Nokdu',ARRAY['조선로코 녹두전','The Tale of Nokdu','조선로코녹두전']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('알함브라 궁전의 추억','Memories of the Alhambra',ARRAY['알함브라 궁전의 추억','Memories of the Alhambra','알함브라궁전의추억']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('라디오 로맨스','Radio Romance',ARRAY['라디오 로맨스','Radio Romance','라디오로맨스']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('으라차차 와이키키','Welcome to Waikiki',ARRAY['으라차차 와이키키','Welcome to Waikiki','으라차차와이키키']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published'),
('블랙','Black',ARRAY['블랙','Black']::text[],2017,'OCN',ARRAY['Drama']::text[],'published'),
('7일의 왕비','Queen for Seven Days',ARRAY['7일의 왕비','Queen for Seven Days','7일의왕비']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('비밀의 숲','Stranger',ARRAY['비밀의 숲','Stranger','비밀의숲']::text[],2017,'tvN',ARRAY['스릴러','법률']::text[],'published'),
('내일 그대와','Tomorrow With You',ARRAY['내일 그대와','Tomorrow With You','내일그대와']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('치즈인더트랩','Cheese in the Trap',ARRAY['치즈인더트랩','Cheese in the Trap']::text[],2016,'tvN',ARRAY['로맨스']::text[],'published'),
('몰랑이','Molang',ARRAY['몰랑이','Molang']::text[],2016,'Disney Jr.',ARRAY['Drama']::text[],'published'),
('너를 기억해','Hello Monster',ARRAY['너를 기억해','Hello Monster','너를기억해']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('밤을 걷는 선비','Scholar Who Walks the Night',ARRAY['밤을 걷는 선비','Scholar Who Walks the Night','밤을걷는선비']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('퐁당퐁당 Love','Splash Splash Love',ARRAY['퐁당퐁당 Love','Splash Splash Love','퐁당퐁당Love']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('맨도롱 또똣','Warm and Cozy',ARRAY['맨도롱 또똣','Warm and Cozy','맨도롱또똣']::text[],2015,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내겐 너무 사랑스러운 그녀','My Lovely Girl',ARRAY['내겐 너무 사랑스러운 그녀','My Lovely Girl','내겐너무사랑스러운그녀']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('야경꾼 일지','Night Watchman''s Journal',ARRAY['야경꾼 일지','Night Watchman''s Journal','야경꾼일지']::text[],2014,'MBC',ARRAY['Drama']::text[],'published'),
('예쁜 남자','Bel Ami',ARRAY['예쁜 남자','Bel Ami','예쁜남자']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('불의 여신 정이','Goddess of Fire',ARRAY['불의 여신 정이','Goddess of Fire','불의여신정이']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('응답하라 1994','Reply 1994',ARRAY['응답하라 1994','Reply 1994','응답하라1994']::text[],2013,'tvN',ARRAY['로맨스','청춘']::text[],'published'),
('그 겨울, 바람이 분다','That Winter, The Wind Blows',ARRAY['그 겨울, 바람이 분다','That Winter, The Wind Blows','그겨울,바람이분다']::text[],2013,'Seoul Broadcasting System',ARRAY['로맨스']::text[],'published'),
('신사의 품격','A Gentleman''s Dignity',ARRAY['신사의 품격','A Gentleman''s Dignity','신사의품격']::text[],2012,'Seoul Broadcasting System',ARRAY['로맨스','코미디']::text[],'published'),
('빅','Big',ARRAY['빅','Big']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('인현왕후의 남자','Queen In-Hyun''s Man',ARRAY['인현왕후의 남자','Queen In-Hyun''s Man','인현왕후의남자']::text[],2012,'tvN',ARRAY['Drama']::text[],'published'),
('최고의 사랑','The Greatest Love',ARRAY['최고의 사랑','The Greatest Love','최고의사랑']::text[],2011,'MBC',ARRAY['Drama']::text[],'published'),
('추노','Chuno',ARRAY['추노','Chuno']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('찬란한 유산','Brilliant Legacy',ARRAY['찬란한 유산','Brilliant Legacy','찬란한유산']::text[],2009,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('다모','Damo',ARRAY['다모','Damo']::text[],2003,'MBC',ARRAY['Drama']::text[],'published'),
('여름향기','Summer Scent',ARRAY['여름향기','Summer Scent']::text[],2003,'KBS2',ARRAY['Drama']::text[],'published'),
('상도','The Merchant of Joseon',ARRAY['상도','The Merchant of Joseon']::text[],2001,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('폭군의 셰프','Bon Appétit, Your Majesty',ARRAY['폭군의 셰프','Bon Appétit, Your Majesty','폭군의셰프']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('다 이루어질지니','Genie, Make a Wish',ARRAY['다 이루어질지니','Genie, Make a Wish','다이루어질지니']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('굿보이','Good Boy',ARRAY['굿보이','Good Boy']::text[],2025,'JTBC',ARRAY['Drama']::text[],'published'),
('별들에게 물어봐','When the Stars Gossip',ARRAY['별들에게 물어봐','When the Stars Gossip','별들에게물어봐']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('더 에이트 쇼','The 8 Show',ARRAY['더 에이트 쇼','The 8 Show','더에이트쇼']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('힙(HIP)하게','Behind your Touch',ARRAY['힙(HIP)하게','Behind your Touch']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('정신병동에도 아침이 와요','Daily Dose of Sunshine',ARRAY['정신병동에도 아침이 와요','Daily Dose of Sunshine','정신병동에도아침이와요']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이두나!','Doona!',ARRAY['이두나!','Doona!']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이번 생도 잘 부탁해','See You in My 19th Life',ARRAY['이번 생도 잘 부탁해','See You in My 19th Life','이번생도잘부탁해']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('웰컴투 삼달리','Welcome to Samdalri',ARRAY['웰컴투 삼달리','Welcome to Samdalri','웰컴투삼달리']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('어게인 마이 라이프','Again My Life',ARRAY['어게인 마이 라이프','Again My Life','어게인마이라이프']::text[],2022,'SBS',ARRAY['Drama']::text[],'published'),
('고스트 닥터','Ghost Doctor',ARRAY['고스트 닥터','Ghost Doctor','고스트닥터']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('무브 투 헤븐: 나는 유품정리사입니다','Move to Heaven',ARRAY['무브 투 헤븐: 나는 유품정리사입니다','Move to Heaven','무브투헤븐:나는유품정리사입니다']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('나빌레라','Navillera',ARRAY['나빌레라','Navillera']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('알고있지만','Nevertheless',ARRAY['알고있지만','Nevertheless']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('아기상어 올리와 윌리엄','Baby Shark''s Big Show!',ARRAY['아기상어 올리와 윌리엄','Baby Shark''s Big Show!','아기상어올리와윌리엄']::text[],2020,'Nickelodeon',ARRAY['Drama']::text[],'published'),
('편의점 샛별이','Backstreet Rookie',ARRAY['편의점 샛별이','Backstreet Rookie','편의점샛별이']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('도도솔솔라라솔','Do Do Sol Sol La La Sol',ARRAY['도도솔솔라라솔','Do Do Sol Sol La La Sol']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('인간수업','Extracurricular',ARRAY['인간수업','Extracurricular']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('나 홀로 그대','My Holo Love',ARRAY['나 홀로 그대','My Holo Love','나홀로그대']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('쌍갑포차','Mystic Pop-up Bar',ARRAY['쌍갑포차','Mystic Pop-up Bar']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('날씨가 좋으면 찾아가겠어요','When the Weather Is Fine',ARRAY['날씨가 좋으면 찾아가겠어요','When the Weather Is Fine','날씨가좋으면찾아가겠어요']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('어비스','Abyss',ARRAY['어비스','Abyss']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('우아한 가','Graceful Family',ARRAY['우아한 가','Graceful Family','우아한가']::text[],2019,'Maeil Broadcasting Network',ARRAY['Drama']::text[],'published'),
('검색어를 입력하세요: www','Search: WWW',ARRAY['검색어를 입력하세요: www','Search: WWW','검색어를입력하세요:www']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('열혈사제','The Fiery Priest',ARRAY['열혈사제','The Fiery Priest']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('무법 변호사','Lawless Lawyer',ARRAY['무법 변호사','Lawless Lawyer','무법변호사']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('나의 아저씨','My Mister',ARRAY['나의 아저씨','My Mister','나의아저씨']::text[],2018,'tvN',ARRAY['드라마']::text[],'published'),
('내 뒤에 테리우스','My Secret Terrius',ARRAY['내 뒤에 테리우스','My Secret Terrius','내뒤에테리우스']::text[],2018,'MBC',ARRAY['Drama']::text[],'published'),
('서른이지만 열일곱입니다','Still 17',ARRAY['서른이지만 열일곱입니다','Still 17','서른이지만열일곱입니다']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('슈츠','Suits',ARRAY['슈츠','Suits']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('황후의 품격','The Last Empress',ARRAY['황후의 품격','The Last Empress','황후의품격']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('여우각시별','Where Stars Land',ARRAY['여우각시별','Where Stars Land']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('사랑의 온도','Temperature of Love',ARRAY['사랑의 온도','Temperature of Love','사랑의온도']::text[],2017,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('하백의 신부 2017','The Bride of Habaek',ARRAY['하백의 신부 2017','The Bride of Habaek','하백의신부2017']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('보이스','Voice',ARRAY['보이스','Voice']::text[],2017,'OCN',ARRAY['스릴러']::text[],'published'),
('또 오해영','Another Miss Oh',ARRAY['또 오해영','Another Miss Oh','또오해영']::text[],2016,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('무림학교','Moorim School',ARRAY['무림학교','Moorim School']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('우리 옆집에 EXO가 산다','EXO Next Door',ARRAY['우리 옆집에 EXO가 산다','EXO Next Door','우리옆집에EXO가산다']::text[],2015,'JTBC2',ARRAY['Drama']::text[],'published'),
('하이드 지킬, 나','Jekyll and Me',ARRAY['하이드 지킬, 나','Jekyll and Me','하이드지킬,나']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('가면','Mask',ARRAY['가면','Mask']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('리멤버 - 아들의 전쟁','Remember: War of the Son',ARRAY['리멤버 - 아들의 전쟁','Remember: War of the Son','리멤버-아들의전쟁']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('조선 총잡이','Gunman in Joseon',ARRAY['조선 총잡이','Gunman in Joseon','조선총잡이']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('하이스쿨 러브온','Hi! School: Love On',ARRAY['하이스쿨 러브온','Hi! School: Love On','하이스쿨러브온']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('괜찮아, 사랑이야','It''s Okay, That''s Love',ARRAY['괜찮아, 사랑이야','It''s Okay, That''s Love','괜찮아,사랑이야']::text[],2014,'SBS',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);