INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('가족끼리 왜 이래','What Happens to My Family?',ARRAY['가족끼리 왜 이래','What Happens to My Family?','가족끼리왜이래']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('더킹2Hearts','The King 2 Hearts',ARRAY['더킹2Hearts','The King 2 Hearts']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('마의','The King''s Doctor',ARRAY['마의','The King''s Doctor']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내게 거짓말을 해봐','Lie to Me',ARRAY['내게 거짓말을 해봐','Lie to Me','내게거짓말을해봐']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('공주의 남자','The Princess'' Man',ARRAY['공주의 남자','The Princess'' Man','공주의남자']::text[],2011,'KBS2',ARRAY['Drama']::text[],'published'),
('대물','Big Thing',ARRAY['대물','Big Thing']::text[],2010,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('매리는 외박중','Mary Stayed Out All Night',ARRAY['매리는 외박중','Mary Stayed Out All Night','매리는외박중']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('황진이','Hwang Jini',ARRAY['황진이','Hwang Jini']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('봄의 왈츠','Spring Waltz',ARRAY['봄의 왈츠','Spring Waltz','봄의왈츠']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('킬러들의 쇼핑몰','A Shop for Killers',ARRAY['킬러들의 쇼핑몰','A Shop for Killers','킬러들의쇼핑몰']::text[],2024,'Star',ARRAY['Drama']::text[],'published'),
('낮과 밤이 다른 그녀','Miss Night and Day',ARRAY['낮과 밤이 다른 그녀','Miss Night and Day','낮과밤이다른그녀']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('피라미드 게임','Pyramid Game',ARRAY['피라미드 게임','Pyramid Game','피라미드게임']::text[],2024,'TVING',ARRAY['Drama']::text[],'published'),
('히어로는 아닙니다만','The Atypical Family',ARRAY['히어로는 아닙니다만','The Atypical Family','히어로는아닙니다만']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('너의 시간 속으로','A Time Called You',ARRAY['너의 시간 속으로','A Time Called You','너의시간속으로']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('택배기사','Black Knight',ARRAY['택배기사','Black Knight']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('셀러브리티','Celebrity',ARRAY['셀러브리티','Celebrity']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이 연애는 불가항력','Destined With You',ARRAY['이 연애는 불가항력','Destined With You','이연애는불가항력']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('연애대전','Love to Hate You',ARRAY['연애대전','Love to Hate You']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('마스크걸','Mask Girl',ARRAY['마스크걸','Mask Girl']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('천원짜리 변호사','One Dollar Lawyer',ARRAY['천원짜리 변호사','One Dollar Lawyer','천원짜리변호사']::text[],2022,'SBS',ARRAY['Drama']::text[],'published'),
('우리들의 블루스','Our Blues',ARRAY['우리들의 블루스','Our Blues','우리들의블루스']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('썸바디','Somebody',ARRAY['썸바디','Somebody']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('안나라수마나라','The Sound of Magic',ARRAY['안나라수마나라','The Sound of Magic']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('간 떨어지는 동거','My Roommate is a Gumiho',ARRAY['간 떨어지는 동거','My Roommate is a Gumiho','간떨어지는동거']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('원 더 우먼','One the Woman',ARRAY['원 더 우먼','One the Woman','원더우먼']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('대박부동산','Sell Your Haunted House',ARRAY['대박부동산','Sell Your Haunted House']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('오월의 청춘','Youth of May',ARRAY['오월의 청춘','Youth of May','오월의청춘']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('앨리스','Alice',ARRAY['앨리스','Alice']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('그 남자의 기억법','Find Me in Your Memory',ARRAY['그 남자의 기억법','Find Me in Your Memory','그남자의기억법']::text[],2020,'MBC',ARRAY['Drama']::text[],'published'),
('키포와 신기한 동물들','Kipo and the Age of Wonderbeasts',ARRAY['키포와 신기한 동물들','Kipo and the Age of Wonderbeasts','키포와신기한동물들']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('어서와','Welcome',ARRAY['어서와','Welcome']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('닥터 프리즈너','Doctor Prisoner',ARRAY['닥터 프리즈너','Doctor Prisoner','닥터프리즈너']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('열여덟의 순간','The Moment of 18',ARRAY['열여덟의 순간','The Moment of 18','열여덟의순간']::text[],2019,'JTBC',ARRAY['Drama']::text[],'published'),
('사의 찬미','The Hymn of Death',ARRAY['사의 찬미','The Hymn of Death','사의찬미']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('크리미널 마인드','Criminal Minds',ARRAY['크리미널 마인드','Criminal Minds','크리미널마인드']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('최고의 한방','Hit the Top',ARRAY['최고의 한방','Hit the Top','최고의한방']::text[],2017,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('그녀는 거짓말을 너무 사랑해','The Liar and His Lover',ARRAY['그녀는 거짓말을 너무 사랑해','The Liar and His Lover','그녀는거짓말을너무사랑해']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('돌아와요 아저씨','Come Back Mister',ARRAY['돌아와요 아저씨','Come Back Mister','돌아와요아저씨']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('사랑하는 은동아','Beloved Eun-dong',ARRAY['사랑하는 은동아','Beloved Eun-dong','사랑하는은동아']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('순정에 반하다','Falling for Innocence',ARRAY['순정에 반하다','Falling for Innocence','순정에반하다']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('상류사회','High Society',ARRAY['상류사회','High Society']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('하녀들','Maids',ARRAY['하녀들','Maids']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('두번째 스무살','Second 20s',ARRAY['두번째 스무살','Second 20s','두번째스무살']::text[],2015,'tvN',ARRAY['Drama']::text[],'published'),
('트라이앵글','Triangle',ARRAY['트라이앵글','Triangle']::text[],2014,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('7급 공무원','7th Grade Civil Servant',ARRAY['7급 공무원','7th Grade Civil Servant','7급공무원']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('야왕','Queen of Ambition',ARRAY['야왕','Queen of Ambition']::text[],2013,'SBS',ARRAY['Drama']::text[],'published'),
('투웍스','Two Weeks',ARRAY['투웍스','Two Weeks']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('천일의 약속','A Thousand Days'' Promise',ARRAY['천일의 약속','A Thousand Days'' Promise','천일의약속']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('꽃미남 라면가게','Flower Boy Ramen Shop',ARRAY['꽃미남 라면가게','Flower Boy Ramen Shop','꽃미남라면가게']::text[],2011,'tvN',ARRAY['Drama']::text[],'published'),
('영광의 재인','Glory Jane',ARRAY['영광의 재인','Glory Jane','영광의재인']::text[],2011,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('계백','Gyebaek',ARRAY['계백','Gyebaek']::text[],2011,'MBC',ARRAY['Drama']::text[],'published'),
('주간 아이돌','Weekly Idol',ARRAY['주간 아이돌','Weekly Idol','주간아이돌']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('아테나: 전쟁의 여신','Athena: Goddess of War',ARRAY['아테나: 전쟁의 여신','Athena: Goddess of War','아테나:전쟁의여신']::text[],2010,'SBS',ARRAY['Drama']::text[],'published'),
('아가씨를 부탁해','My Fair Lady',ARRAY['아가씨를 부탁해','My Fair Lady','아가씨를부탁해']::text[],2009,'KBS2',ARRAY['Drama']::text[],'published'),
('에덴의 동쪽','East of Eden',ARRAY['에덴의 동쪽','East of Eden','에덴의동쪽']::text[],2008,'MBC',ARRAY['Drama']::text[],'published'),
('우리 결혼했어요','We Got Married',ARRAY['우리 결혼했어요','We Got Married','우리결혼했어요']::text[],2008,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('왕과 나','The King and I',ARRAY['왕과 나','The King and I','왕과나']::text[],2007,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('개와 늑대의 시간','Time Between Dog and Wolf',ARRAY['개와 늑대의 시간','Time Between Dog and Wolf','개와늑대의시간']::text[],2007,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('환상의 커플','Couple or Trouble',ARRAY['환상의 커플','Couple or Trouble','환상의커플']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('별은 내 가슴에','Star in My Heart',ARRAY['별은 내 가슴에','Star in My Heart','별은내가슴에']::text[],1997,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('첫사랑','First Love',ARRAY['첫사랑','First Love']::text[],1996,'KBS2',ARRAY['Drama']::text[],'published'),
('여명의 눈동자','Eyes of Dawn',ARRAY['여명의 눈동자','Eyes of Dawn','여명의눈동자']::text[],1991,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('21세기 대군부인','Perfect Crown',ARRAY['21세기 대군부인','Perfect Crown','21세기대군부인']::text[],2026,'MBC',ARRAY['Drama']::text[],'published'),
('동궁','The East Palace',ARRAY['동궁','The East Palace']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('에스콰이어: 변호사를 꿈꾸는 변호사들','Beyond the Bar',ARRAY['에스콰이어: 변호사를 꿈꾸는 변호사들','Beyond the Bar','에스콰이어:변호사를꿈꾸는변호사들']::text[],2025,'JTBC',ARRAY['Drama']::text[],'published'),
('탄금','Dear Hongrang',ARRAY['탄금','Dear Hongrang']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('선의의 경쟁','Friendly Rivalry',ARRAY['선의의 경쟁','Friendly Rivalry','선의의경쟁']::text[],2025,'U+Mobile',ARRAY['Drama']::text[],'published'),
('스터디그룹','Study Group',ARRAY['스터디그룹','Study Group']::text[],2025,'TVING',ARRAY['Drama']::text[],'published'),
('자백의 대가','The Price of Confession',ARRAY['자백의 대가','The Price of Confession','자백의대가']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('살인자ㅇ난감','A Killer Paradox',ARRAY['살인자ㅇ난감','A Killer Paradox']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('닭강정','Chicken Nugget',ARRAY['닭강정','Chicken Nugget']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('조립식 가족','Family by Choice',ARRAY['조립식 가족','Family by Choice','조립식가족']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('재벌X형사','Flex X Cop',ARRAY['재벌X형사','Flex X Cop']::text[],2024,'SBS',ARRAY['Drama']::text[],'published'),
('종말의 바보','Goodbye Earth',ARRAY['종말의 바보','Goodbye Earth','종말의바보']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('아무도 없는 숲속에서','The Frog',ARRAY['아무도 없는 숲속에서','The Frog','아무도없는숲속에서']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('지금 거신 전화는','When the Phone Rings',ARRAY['지금 거신 전화는','When the Phone Rings','지금거신전화는']::text[],2024,'MBC',ARRAY['Drama']::text[],'published'),
('딜리버리 맨!','Delivery Man',ARRAY['딜리버리 맨!','Delivery Man','딜리버리맨!']::text[],2023,'Genie',ARRAY['Drama']::text[],'published'),
('무빙','Moving',ARRAY['무빙','Moving']::text[],2023,'Hulu',ARRAY['액션','판타지']::text[],'published'),
('슈퍼맨과 나의 모험','My Adventures with Superman',ARRAY['슈퍼맨과 나의 모험','My Adventures with Superman','슈퍼맨과나의모험']::text[],2023,'Adult Swim',ARRAY['Drama']::text[],'published'),
('연인','My Dearest',ARRAY['연인','My Dearest']::text[],2023,'MBC',ARRAY['Drama']::text[],'published'),
('퀸메이커','Queenmaker',ARRAY['퀸메이커','Queenmaker']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('힘쎈여자 강남순','Strong Girl Nam-soon',ARRAY['힘쎈여자 강남순','Strong Girl Nam-soon','힘쎈여자강남순']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('붉은 단심','Bloody Heart',ARRAY['붉은 단심','Bloody Heart','붉은단심']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('미남당','Café Minamdang',ARRAY['미남당','Café Minamdang']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('커넥트','Connect',ARRAY['커넥트','Connect']::text[],2022,'Hulu',ARRAY['Drama']::text[],'published'),
('월수금화목토','Love in Contract',ARRAY['월수금화목토','Love in Contract']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('군검사 도베르만','Military Prosecutor Doberman',ARRAY['군검사 도베르만','Military Prosecutor Doberman','군검사도베르만']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('어쩌다 전원일기','Once Upon a Small Town',ARRAY['어쩌다 전원일기','Once Upon a Small Town','어쩌다전원일기']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('조선 정신과 의사 유세풍','Poong, the Joseon Psychiatrist',ARRAY['조선 정신과 의사 유세풍','Poong, the Joseon Psychiatrist','조선정신과의사유세풍']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('3인칭 복수','Revenge of Others',ARRAY['3인칭 복수','Revenge of Others','3인칭복수']::text[],2022,'Star',ARRAY['Drama']::text[],'published'),
('사운드트랙 #1','Soundtrack #1',ARRAY['사운드트랙 #1','Soundtrack #1','사운드트랙#1']::text[],2022,'Star',ARRAY['Drama']::text[],'published'),
('금수저','The Golden Spoon',ARRAY['금수저','The Golden Spoon']::text[],2022,'MBC',ARRAY['Drama']::text[],'published'),
('괴물','Beyond Evil',ARRAY['괴물','Beyond Evil']::text[],2021,'JTBC',ARRAY['스릴러','범죄']::text[],'published'),
('달리와 감자탕','Dali and Cocky Prince',ARRAY['달리와 감자탕','Dali and Cocky Prince','달리와감자탕']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('홍천기','Lovers of the Red Sky',ARRAY['홍천기','Lovers of the Red Sky']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('지금 헤어지는 중입니다.','Now, We Are Breaking Up',ARRAY['지금 헤어지는 중입니다.','Now, We Are Breaking Up','지금헤어지는중입니다.']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('학교 2021','School 2021',ARRAY['학교 2021','School 2021','학교2021']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('시지프스 : the myth','Sisyphus: The Myth',ARRAY['시지프스 : the myth','Sisyphus: The Myth','시지프스:themyth']::text[],2021,'JTBC',ARRAY['Drama']::text[],'published'),
('꽃 피면 달 생각하고','When Flowers Bloom, I Think of the Moon',ARRAY['꽃 피면 달 생각하고','When Flowers Bloom, I Think of the Moon','꽃피면달생각하고']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('유미의 세포들','Yumi''s Cells',ARRAY['유미의 세포들','Yumi''s Cells','유미의세포들']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('18 어게인','18 Again',ARRAY['18 어게인','18 Again','18어게인']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('암행어사: 조선비밀수사단','Royal Secret Agent',ARRAY['암행어사: 조선비밀수사단','Royal Secret Agent','암행어사:조선비밀수사단']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('좀비탐정','Zombie Detective',ARRAY['좀비탐정','Zombie Detective']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('의사요한','Doctor John',ARRAY['의사요한','Doctor John']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('멈추고 싶은 순간 : 어바웃 타임','About Time',ARRAY['멈추고 싶은 순간 : 어바웃 타임','About Time','멈추고싶은순간:어바웃타임']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('하나뿐인 내편','My Only One',ARRAY['하나뿐인 내편','My Only One','하나뿐인내편']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('뷰티 인사이드','The Beauty Inside',ARRAY['뷰티 인사이드','The Beauty Inside','뷰티인사이드']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published'),
('병원선','Hospital Ship',ARRAY['병원선','Hospital Ship']::text[],2017,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('맨투맨','Man to Man',ARRAY['맨투맨','Man to Man']::text[],2017,'JTBC',ARRAY['Drama']::text[],'published'),
('아버지가 이상해','My Father is Strange',ARRAY['아버지가 이상해','My Father is Strange','아버지가이상해']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('애타는 로맨스','My Secret Romance',ARRAY['애타는 로맨스','My Secret Romance','애타는로맨스']::text[],2017,'OCN',ARRAY['Drama']::text[],'published'),
('변혁의 사랑','Revolutionary Love',ARRAY['변혁의 사랑','Revolutionary Love','변혁의사랑']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('군주','Ruler: Master of the Mask',ARRAY['군주','Ruler: Master of the Mask']::text[],2017,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('더 패키지','The Package',ARRAY['더 패키지','The Package','더패키지']::text[],2017,'JTBC',ARRAY['Drama']::text[],'published'),
('질투의 화신','Don''t Dare to Dream',ARRAY['질투의 화신','Don''t Dare to Dream','질투의화신']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('옥중화','Flowers of the Prison',ARRAY['옥중화','Flowers of the Prison']::text[],2016,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('청춘시대','Hello, My Twenties!',ARRAY['청춘시대','Hello, My Twenties!']::text[],2016,'JTBC',ARRAY['Drama']::text[],'published'),
('대박','The Royal Gambler',ARRAY['대박','The Royal Gambler']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('해적왕 작스톰','Zak Storm',ARRAY['해적왕 작스톰','Zak Storm','해적왕작스톰']::text[],2016,'Canal J',ARRAY['Drama']::text[],'published'),
('발칙하게 고고','Cheer Up!',ARRAY['발칙하게 고고','Cheer Up!','발칙하게고고']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('디데이','D-Day',ARRAY['디데이','D-Day']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('애인 있어요','I Have a Lover',ARRAY['애인 있어요','I Have a Lover','애인있어요']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('빛나거나 미치거나','Shine or Go Crazy',ARRAY['빛나거나 미치거나','Shine or Go Crazy','빛나거나미치거나']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('화정','Splendid Politics',ARRAY['화정','Splendid Politics']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('엔젤 아이즈','Angel Eyes',ARRAY['엔젤 아이즈','Angel Eyes','엔젤아이즈']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('나쁜 녀석들','Bad Guys',ARRAY['나쁜 녀석들','Bad Guys','나쁜녀석들']::text[],2014,'OCN',ARRAY['범죄']::text[],'published'),
('백년의 신부','Bride of the Century',ARRAY['백년의 신부','Bride of the Century','백년의신부']::text[],2014,'TV CHOSUN',ARRAY['Drama']::text[],'published'),
('운명처럼 널 사랑해','Fated to Love You',ARRAY['운명처럼 널 사랑해','Fated to Love You','운명처럼널사랑해']::text[],2014,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('왕의 얼굴','The King''s Face',ARRAY['왕의 얼굴','The King''s Face','왕의얼굴']::text[],2014,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('삼총사','The Three Musketeers',ARRAY['삼총사','The Three Musketeers']::text[],2014,'tvN',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);