INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('쓰리 데이즈','Three Days',ARRAY['쓰리 데이즈','Three Days','쓰리데이즈']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('너희들은 포위됐다','You''re All Surrounded',ARRAY['너희들은 포위됐다','You''re All Surrounded','너희들은포위됐다']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('총리와 나','Prime Minister and I',ARRAY['총리와 나','Prime Minister and I','총리와나']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('최고다 이순신','You''re the Best, Lee Soon-shin',ARRAY['최고다 이순신','You''re the Best, Lee Soon-shin','최고다이순신']::text[],2013,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('시계마을 티키톡!','Tickety Toc',ARRAY['시계마을 티키톡!','Tickety Toc','시계마을티키톡!']::text[],2012,'Korea Educational Broadcasting System',ARRAY['Drama']::text[],'published'),
('무사 백동수','Warrior Baek Dong-soo',ARRAY['무사 백동수','Warrior Baek Dong-soo','무사백동수']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('공부의 신','Master of Study',ARRAY['공부의 신','Master of Study','공부의신']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('오! 마이 레이디','Oh! My Lady',ARRAY['오! 마이 레이디','Oh! My Lady','오!마이레이디']::text[],2010,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('변신자동차 또봇','Tobot',ARRAY['변신자동차 또봇','Tobot','변신자동차또봇']::text[],2010,NULL,ARRAY['Drama']::text[],'published'),
('신데렐라 맨','Cinderella Man',ARRAY['신데렐라 맨','Cinderella Man','신데렐라맨']::text[],2009,'MBC',ARRAY['Drama']::text[],'published'),
('베토벤 바이러스','Beethoven Virus',ARRAY['베토벤 바이러스','Beethoven Virus','베토벤바이러스']::text[],2008,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('쾌도 홍길동','Hong Gil Dong',ARRAY['쾌도 홍길동','Hong Gil Dong','쾌도홍길동']::text[],2008,'KBS2',ARRAY['Drama']::text[],'published'),
('바람의 나라','The Kingdom of The Winds',ARRAY['바람의 나라','The Kingdom of The Winds','바람의나라']::text[],2008,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('고맙습니다','Thank You',ARRAY['고맙습니다','Thank You']::text[],2007,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('슬픈 연가','Sad Love Story',ARRAY['슬픈 연가','Sad Love Story','슬픈연가']::text[],2005,'MBC',ARRAY['Drama']::text[],'published'),
('쾌걸춘향','Sassy Girl Chun-hyang',ARRAY['쾌걸춘향','Sassy Girl Chun-hyang']::text[],2005,'GMA Network',ARRAY['Drama']::text[],'published'),
('러브스토리 인 하버드','Love Story in Harvard',ARRAY['러브스토리 인 하버드','Love Story in Harvard','러브스토리인하버드']::text[],2004,'SBS',ARRAY['Drama']::text[],'published'),
('월간남친','Boyfriend on Demand',ARRAY['월간남친','Boyfriend on Demand']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('멋진 신세계','My Royal Nemesis',ARRAY['멋진 신세계','My Royal Nemesis','멋진신세계']::text[],2026,'SBS',ARRAY['Drama']::text[],'published'),
('더 원더풀스','The Wonderfools',ARRAY['더 원더풀스','The Wonderfools','더원더풀스']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('견우와 선녀','Head over Heels',ARRAY['견우와 선녀','Head over Heels','견우와선녀']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('그놈은 흑염룡','My Dearest Nemesis',ARRAY['그놈은 흑염룡','My Dearest Nemesis','그놈은흑염룡']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('뉴토피아','Newtopia',ARRAY['뉴토피아','Newtopia']::text[],2025,'Coupang Play',ARRAY['Drama']::text[],'published'),
('언젠가는 슬기로울 전공의생활','Resident Playbook',ARRAY['언젠가는 슬기로울 전공의생활','Resident Playbook','언젠가는슬기로울전공의생활']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('원경','The Queen Who Crowns',ARRAY['원경','The Queen Who Crowns']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('미녀와 순정남','Beauty and Mr. Romantic',ARRAY['미녀와 순정남','Beauty and Mr. Romantic','미녀와순정남']::text[],2024,'KBS2',ARRAY['Drama']::text[],'published'),
('세작, 매혹된 자들','Captivating the King',ARRAY['세작, 매혹된 자들','Captivating the King','세작,매혹된자들']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('로얄로더','The Impossible Heir',ARRAY['로얄로더','The Impossible Heir']::text[],2024,'Disney+',ARRAY['Drama']::text[],'published'),
('졸업','The Midnight Romance in Hagwon',ARRAY['졸업','The Midnight Romance in Hagwon']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('운수 오진 날','A Bloody Lucky Day',ARRAY['운수 오진 날','A Bloody Lucky Day','운수오진날']::text[],2023,'TVN (Southeast Asia)',ARRAY['Drama']::text[],'published'),
('오늘도 사랑스럽개','A Good Day to Be a Dog',ARRAY['오늘도 사랑스럽개','A Good Day to Be a Dog','오늘도사랑스럽개']::text[],2023,'MBC',ARRAY['Drama']::text[],'published'),
('닥터 차정숙','Doctor Cha Jung-sook',ARRAY['닥터 차정숙','Doctor Cha Jung-sook','닥터차정숙']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('방과 후 전쟁활동','Duty After School',ARRAY['방과 후 전쟁활동','Duty After School','방과후전쟁활동']::text[],2023,'TVING',ARRAY['Drama']::text[],'published'),
('꼭두의 계절','Kokdu: Season of Deity',ARRAY['꼭두의 계절','Kokdu: Season of Deity','꼭두의계절']::text[],2023,'MBC',ARRAY['Drama']::text[],'published'),
('판도라: 조작된 낙원','Pandora: Beneath the Paradise',ARRAY['판도라: 조작된 낙원','Pandora: Beneath the Paradise','판도라:조작된낙원']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('7인의 탈출','The Escape of the Seven',ARRAY['7인의 탈출','The Escape of the Seven','7인의탈출']::text[],2023,'SBS',ARRAY['Drama']::text[],'published'),
('나쁜 엄마','The Good Bad Mother',ARRAY['나쁜 엄마','The Good Bad Mother','나쁜엄마']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('진짜가 나타났다!','The Real Has Come!',ARRAY['진짜가 나타났다!','The Real Has Come!','진짜가나타났다!']::text[],2023,'KBS2',ARRAY['Drama']::text[],'published'),
('꽃선비 열애사','The Secret Romantic Guesthouse',ARRAY['꽃선비 열애사','The Secret Romantic Guesthouse','꽃선비열애사']::text[],2023,'SBS',ARRAY['Drama']::text[],'published'),
('크레이지 러브','Crazy Love',ARRAY['크레이지 러브','Crazy Love','크레이지러브']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('당신이 소원을 말하면','If You Wish Upon Me',ARRAY['당신이 소원을 말하면','If You Wish Upon Me','당신이소원을말하면']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('키스 식스 센스','Kiss Sixth Sense',ARRAY['키스 식스 센스','Kiss Sixth Sense','키스식스센스']::text[],2022,'Disney+',ARRAY['Drama']::text[],'published'),
('너에게 가는 속도 493KM','Love All Play',ARRAY['너에게 가는 속도 493KM','Love All Play','너에게가는속도493KM']::text[],2022,'KBS2',ARRAY['Drama']::text[],'published'),
('나의 해방일지','My Liberation Notes',ARRAY['나의 해방일지','My Liberation Notes','나의해방일지']::text[],2022,'JTBC',ARRAY['드라마']::text[],'published'),
('수리남','Narco-Saints',ARRAY['수리남','Narco-Saints']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('블랙의 신부','Remarriage & Desires',ARRAY['블랙의 신부','Remarriage & Desires','블랙의신부']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('서른, 아홉','Thirty-Nine',ARRAY['서른, 아홉','Thirty-Nine','서른,아홉']::text[],2022,'JTBC',ARRAY['Drama']::text[],'published'),
('내일','Tomorrow',ARRAY['내일','Tomorrow']::text[],2022,'MBC',ARRAY['Drama']::text[],'published'),
('배드 앤 크레이지','Bad and Crazy',ARRAY['배드 앤 크레이지','Bad and Crazy','배드앤크레이지']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('어느 날 우리 집 현관으로 멸망이 들어왔다','Doom at Your Service',ARRAY['어느 날 우리 집 현관으로 멸망이 들어왔다','Doom at Your Service','어느날우리집현관으로멸망이들어왔다']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('지리산','Jirisan',ARRAY['지리산','Jirisan']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('로스쿨','Law School',ARRAY['로스쿨','Law School']::text[],2021,'JTBC',ARRAY['Drama']::text[],'published'),
('멜랑꼴리아','Melancholia',ARRAY['멜랑꼴리아','Melancholia']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('라켓소년단','Racket Boys',ARRAY['라켓소년단','Racket Boys']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('달이 뜨는 강','River Where the Moon Rises',ARRAY['달이 뜨는 강','River Where the Moon Rises','달이뜨는강']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('모범택시','Taxi Driver',ARRAY['모범택시','Taxi Driver']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('두 번째 남편','The Second Husband',ARRAY['두 번째 남편','The Second Husband','두번째남편']::text[],2021,'MBC',ARRAY['Drama']::text[],'published'),
('바람피면 죽는다','Cheat on Me, if You Can',ARRAY['바람피면 죽는다','Cheat on Me, if You Can','바람피면죽는다']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('굿캐스팅','Good Casting',ARRAY['굿캐스팅','Good Casting']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('메모리스트','Memorist',ARRAY['메모리스트','Memorist']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('경우의 수','More Than Friends',ARRAY['경우의 수','More Than Friends','경우의수']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('보건교사 안은영','The School Nurse Files',ARRAY['보건교사 안은영','The School Nurse Files','보건교사안은영']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('화양연화','When My Love Blooms',ARRAY['화양연화','When My Love Blooms']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('아름다운 세상','Beautiful World',ARRAY['아름다운 세상','Beautiful World','아름다운세상']::text[],2019,'JTBC',ARRAY['Drama']::text[],'published'),
('지정생존자','Designated Survivor: 60 Days',ARRAY['지정생존자','Designated Survivor: 60 Days']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('꽃파당: 조선혼담공작소','Flower Crew: Joseon Marriage Agency',ARRAY['꽃파당: 조선혼담공작소','Flower Crew: Joseon Marriage Agency','꽃파당:조선혼담공작소']::text[],2019,'JTBC',ARRAY['Drama']::text[],'published'),
('해치','Haechi',ARRAY['해치','Haechi']::text[],2019,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('사이코메트리 그녀석','He Is Psychometric',ARRAY['사이코메트리 그녀석','He Is Psychometric','사이코메트리그녀석']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('스토브리그','Hot Stove League',ARRAY['스토브리그','Hot Stove League']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('첫사랑은 처음이라서','My First First Love',ARRAY['첫사랑은 처음이라서','My First First Love','첫사랑은처음이라서']::text[],2019,'Netflix',ARRAY['Drama']::text[],'published'),
('일단 뜨겁게 청소하라','Clean with Passion for Now',ARRAY['일단 뜨겁게 청소하라','Clean with Passion for Now','일단뜨겁게청소하라']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published'),
('대군 - 사랑을 그리다','Grand Prince',ARRAY['대군 - 사랑을 그리다','Grand Prince','대군-사랑을그리다']::text[],2018,'TV CHOSUN',ARRAY['Drama']::text[],'published'),
('위대한 유혹자','Tempted',ARRAY['위대한 유혹자','Tempted','위대한유혹자']::text[],2018,'MBC',ARRAY['Drama']::text[],'published'),
('김과장','Good Manager',ARRAY['김과장','Good Manager']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('피고인','Innocent Defendant',ARRAY['피고인','Innocent Defendant']::text[],2017,'SBS',ARRAY['Drama']::text[],'published'),
('내성적인 보스','Introverted Boss',ARRAY['내성적인 보스','Introverted Boss','내성적인보스']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('미씽9','Missing 9',ARRAY['미씽9','Missing 9']::text[],2017,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('슬기로운 감빵생활','Prison Playbook',ARRAY['슬기로운 감빵생활','Prison Playbook','슬기로운감빵생활']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('역적 : 백성을 훔친 도적','Rebel: Thief Who Stole the People',ARRAY['역적 : 백성을 훔친 도적','Rebel: Thief Who Stole the People','역적:백성을훔친도적']::text[],2017,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('다시 만난 세계','Reunited Worlds',ARRAY['다시 만난 세계','Reunited Worlds','다시만난세계']::text[],2017,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('터널','Tunnel',ARRAY['터널','Tunnel']::text[],2017,'OCN',ARRAY['스릴러']::text[],'published'),
('미녀 공심이','Beautiful Gong Shim',ARRAY['미녀 공심이','Beautiful Gong Shim','미녀공심이']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('굿바이 미스터 블랙','Goodbye Mr. Black',ARRAY['굿바이 미스터 블랙','Goodbye Mr. Black','굿바이미스터블랙']::text[],2016,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('운빨로맨스','Lucky Romance',ARRAY['운빨로맨스','Lucky Romance']::text[],2016,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('공항 가는 길','On the Way to the Airport',ARRAY['공항 가는 길','On the Way to the Airport','공항가는길']::text[],2016,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('뱀파이어 탐정','Vampire Detective',ARRAY['뱀파이어 탐정','Vampire Detective','뱀파이어탐정']::text[],2016,'OCN',ARRAY['Drama']::text[],'published'),
('앵그리맘','Angry Mom',ARRAY['앵그리맘','Angry Mom']::text[],2015,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('달려라 방탄','Run BTS',ARRAY['달려라 방탄','Run BTS','달려라방탄']::text[],2015,NULL,ARRAY['Drama']::text[],'published'),
('너를 사랑한 시간','The Time We Were Not in Love',ARRAY['너를 사랑한 시간','The Time We Were Not in Love','너를사랑한시간']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('마녀의 연애','A Witch''s Love',ARRAY['마녀의 연애','A Witch''s Love','마녀의연애']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('앙큼한 돌싱녀','Cunning Single Lady',ARRAY['앙큼한 돌싱녀','Cunning Single Lady','앙큼한돌싱녀']::text[],2014,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('로맨스가 필요해 3','I Need Romance 3',ARRAY['로맨스가 필요해 3','I Need Romance 3','로맨스가필요해3']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('라이어 게임','Liar Game',ARRAY['라이어 게임','Liar Game','라이어게임']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('연애 말고 결혼','Marriage, Not Dating',ARRAY['연애 말고 결혼','Marriage, Not Dating','연애말고결혼']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('모던파머','Modern Farmer',ARRAY['모던파머','Modern Farmer']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('밀회','Secret Affair',ARRAY['밀회','Secret Affair']::text[],2014,'JTBC',ARRAY['Drama']::text[],'published'),
('비밀의 문','Secret Door',ARRAY['비밀의 문','Secret Door','비밀의문']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('잉여공주','The Idle Mermaid',ARRAY['잉여공주','The Idle Mermaid']::text[],2014,'tvN',ARRAY['Drama']::text[],'published'),
('메디컬 탑팀','Medical Top Team',ARRAY['메디컬 탑팀','Medical Top Team','메디컬탑팀']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('각시탈','Bridal Mask',ARRAY['각시탈','Bridal Mask']::text[],2012,'KBS2',ARRAY['Drama']::text[],'published'),
('패션왕','Fashion King',ARRAY['패션왕','Fashion King']::text[],2012,'SBS',ARRAY['Drama']::text[],'published'),
('유령','Phantom',ARRAY['유령','Phantom']::text[],2012,'SBS',ARRAY['Drama']::text[],'published'),
('닥치고 꽃미남 밴드','Shut Up Flower Boy Band',ARRAY['닥치고 꽃미남 밴드','Shut Up Flower Boy Band','닥치고꽃미남밴드']::text[],2012,'tvN',ARRAY['Drama']::text[],'published'),
('총각네 야채가게','Bachelor''s Vegetable Store',ARRAY['총각네 야채가게','Bachelor''s Vegetable Store','총각네야채가게']::text[],2011,'Channel A',ARRAY['Drama']::text[],'published'),
('뿌리깊은 나무','Deep Rooted Tree',ARRAY['뿌리깊은 나무','Deep Rooted Tree','뿌리깊은나무']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('나도','Me Too',ARRAY['나도','Me Too']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('빠담빠담… 그와 그녀의 심장박동소리','Padam Padam... The Sound of His and Her Heartbeats',ARRAY['빠담빠담… 그와 그녀의 심장박동소리','Padam Padam... The Sound of His and Her Heartbeats','빠담빠담…그와그녀의심장박동소리']::text[],2011,'JTBC',ARRAY['Drama']::text[],'published'),
('로맨스 타운','Romance Town',ARRAY['로맨스 타운','Romance Town','로맨스타운']::text[],2011,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('뱀파이어 검사','Vampire Prosecutor',ARRAY['뱀파이어 검사','Vampire Prosecutor','뱀파이어검사']::text[],2011,'OCN',ARRAY['Drama']::text[],'published'),
('커피하우스','Coffee House',ARRAY['커피하우스','Coffee House']::text[],2010,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('역전의 여왕','Queen of Reversals',ARRAY['역전의 여왕','Queen of Reversals','역전의여왕']::text[],2010,'MBC',ARRAY['Drama']::text[],'published'),
('자명고','Ja Myung Go',ARRAY['자명고','Ja Myung Go']::text[],2009,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('돌아온 일지매','The Return of Iljimae',ARRAY['돌아온 일지매','The Return of Iljimae','돌아온일지매']::text[],2009,'MBC',ARRAY['Drama']::text[],'published'),
('아내의 유혹','Temptation of Wife',ARRAY['아내의 유혹','Temptation of Wife','아내의유혹']::text[],2008,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('너는 내 운명','You Are My Destiny',ARRAY['너는 내 운명','You Are My Destiny','너는내운명']::text[],2008,'KBS 1TV',ARRAY['Drama']::text[],'published'),
('쩐의 전쟁','War of Money',ARRAY['쩐의 전쟁','War of Money','쩐의전쟁']::text[],2007,'SBS',ARRAY['Drama']::text[],'published'),
('거침없이 하이킥!','High Kick!',ARRAY['거침없이 하이킥!','High Kick!','거침없이하이킥!']::text[],2006,'MBC',ARRAY['Drama']::text[],'published'),
('아이언 키드','Iron Kid',ARRAY['아이언 키드','Iron Kid','아이언키드']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('천국의 나무','Tree of Heaven',ARRAY['천국의 나무','Tree of Heaven','천국의나무']::text[],2006,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('굳세어라 금순아','Be Strong',ARRAY['굳세어라 금순아','Be Strong','굳세어라금순아']::text[],2005,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('프라하의 연인','Lovers in Prague',ARRAY['프라하의 연인','Lovers in Prague','프라하의연인']::text[],2005,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('파리의 연인','Lovers in Paris',ARRAY['파리의 연인','Lovers in Paris','파리의연인']::text[],2004,'SBS',ARRAY['로맨스']::text[],'published'),
('올림포스 가디언','Olympus Guardian',ARRAY['올림포스 가디언','Olympus Guardian','올림포스가디언']::text[],2002,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('명성황후','Empress Myeongseong',ARRAY['명성황후','Empress Myeongseong']::text[],2001,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('스프링 피버','Spring Fever',ARRAY['스프링 피버','Spring Fever','스프링피버']::text[],2026,'tvN',ARRAY['Drama']::text[],'published'),
('김부장','Agent Kim Reactivated',ARRAY['김부장','Agent Kim Reactivated']::text[],2026,'SBS',ARRAY['Drama']::text[],'published'),
('얄미운 사랑','Nice to Not Meet You',ARRAY['얄미운 사랑','Nice to Not Meet You','얄미운사랑']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('마녀','The Witch',ARRAY['마녀','The Witch']::text[],2025,'Channel A',ARRAY['Drama']::text[],'published'),
('당신이 죽였다','As You Stood By',ARRAY['당신이 죽였다','As You Stood By','당신이죽였다']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('S라인','S Line',ARRAY['S라인','S Line']::text[],2025,'Vidio',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);