// Shared drama catalog — browse page + detail page both import from here
export type CatalogDrama = {
  id: string;        // URL slug
  dbId: string;      // Supabase UUID
  titleKr: string;
  titleEn: string;
  year: number;
  network: string;
  genresEn: string[];
  genresKr: string[];
  emoji: string;
  descriptionEn: string;
  descriptionKr: string;
};

export const DRAMA_CATALOG: CatalogDrama[] = [
  {
    id: "tangerines",
    dbId: "00000000-0000-0000-0000-000000000001",
    titleKr: "폭싹 속았수다",
    titleEn: "When Life Gives You Tangerines",
    year: 2025,
    network: "Netflix",
    genresEn: ["Drama", "Romance", "Family"],
    genresKr: ["드라마", "로맨스", "가족"],
    emoji: "🍊",
    descriptionEn: "A 70-year tale set in Jeju. Starring IU & Park Bo-gum.",
    descriptionKr: "제주를 배경으로 한 70년 이야기. 아이유, 박보검 주연.",
  },
  {
    id: "my-liberation-notes",
    dbId: "00000000-0000-0000-0000-000000000002",
    titleKr: "나의 해방일지",
    titleEn: "My Liberation Notes",
    year: 2022,
    network: "JTBC",
    genresEn: ["Drama", "Slice of Life"],
    genresKr: ["드라마", "일상"],
    emoji: "🌾",
    descriptionEn: "Three siblings seek liberation from mundane daily commutes.",
    descriptionKr: "경기도 산포에서 서울로 출퇴근하는 세 남매의 일상과 해방.",
  },
  {
    id: "our-blues",
    dbId: "00000000-0000-0000-0000-000000000003",
    titleKr: "우리들의 블루스",
    titleEn: "Our Blues",
    year: 2022,
    network: "tvN",
    genresEn: ["Drama", "Human"],
    genresKr: ["드라마", "휴먼"],
    emoji: "🌊",
    descriptionEn: "Omnibus stories of 16 sweet and bitter lives in Jeju.",
    descriptionKr: "제주 바다를 배경으로 한 열여섯 명의 옴니버스 이야기.",
  },
  {
    id: "moving",
    dbId: "00000000-0000-0000-0000-000000000004",
    titleKr: "무빙",
    titleEn: "Moving",
    year: 2023,
    network: "Disney+",
    genresEn: ["Action", "Fantasy", "Drama"],
    genresKr: ["액션", "판타지", "드라마"],
    emoji: "⚡",
    descriptionEn: "Children with hidden superpowers & their protective parents.",
    descriptionKr: "초능력을 가진 아이들과 그들의 부모 세대의 판타지 액션.",
  },
  {
    id: "hotel-del-luna",
    dbId: "00000000-0000-0000-0000-000000000005",
    titleKr: "호텔 델루나",
    titleEn: "Hotel del Luna",
    year: 2019,
    network: "tvN",
    genresEn: ["Fantasy", "Romance"],
    genresKr: ["판타지", "로맨스"],
    emoji: "🌙",
    descriptionEn: "A mysterious hotel serving souls of the dead in Seoul.",
    descriptionKr: "떠돌이 영혼들을 치료하는 신비로운 호텔 사장의 이야기.",
  },
  {
    id: "crash-landing",
    dbId: "0d632091-f751-403f-8e86-138f29d2241d",
    titleKr: "사랑의 불시착",
    titleEn: "Crash Landing on You",
    year: 2019,
    network: "tvN",
    genresEn: ["Romance", "Drama"],
    genresKr: ["로맨스", "드라마"],
    emoji: "🪂",
    descriptionEn: "A South Korean heiress accidentally paraglides into North Korea.",
    descriptionKr: "북한에 불시착한 재벌 상속녀와 북한 장교의 로맨스.",
  },
  {
    id: "extraordinary-attorney-woo",
    dbId: "6d5765be-e968-43c7-81f6-c0a024aff57e",
    titleKr: "이상한 변호사 우영우",
    titleEn: "Extraordinary Attorney Woo",
    year: 2022,
    network: "ENA",
    genresEn: ["Legal", "Drama"],
    genresKr: ["법정", "드라마"],
    emoji: "🐋",
    descriptionEn: "A brilliant attorney on the autism spectrum tackles legal cases.",
    descriptionKr: "자폐 스펙트럼 장애를 가진 천재 신입 변호사의 성장기.",
  },
  {
    id: "goblin",
    dbId: "f85fec9a-cb38-4f33-bee2-4f8bc8070e2e",
    titleKr: "도깨비",
    titleEn: "Guardian: The Lonely and Great God",
    year: 2016,
    network: "tvN",
    genresEn: ["Fantasy", "Romance"],
    genresKr: ["판타지", "로맨스"],
    emoji: "🕯️",
    descriptionEn: "An immortal goblin and his unlikely companions across time.",
    descriptionKr: "불멸의 삶을 끝내려는 도깨비와 그 신부의 운명적 이야기.",
  },
  {
    id: "reply-1988",
    dbId: "04c64268-36d0-4e7f-9f32-9e735dcb3e80",
    titleKr: "응답하라 1988",
    titleEn: "Reply 1988",
    year: 2015,
    network: "tvN",
    genresEn: ["Drama", "Comedy"],
    genresKr: ["드라마", "코미디"],
    emoji: "📻",
    descriptionEn: "Five childhood friends & their families living in 1988 Seoul.",
    descriptionKr: "1988년 쌍문동 골목 다섯 가족과 친구들의 따뜻한 청춘.",
  },
  {
    id: "alchemy-of-souls",
    dbId: "707d35de-d167-4a2c-acd4-6146c988bdd5",
    titleKr: "환혼",
    titleEn: "Alchemy of Souls",
    year: 2022,
    network: "tvN",
    genresEn: ["Fantasy", "Martial Arts"],
    genresKr: ["판타지", "무협"],
    emoji: "🌀",
    descriptionEn: "A powerful sorceress trapped in a blind woman's body meets a noble master.",
    descriptionKr: "영혼이 뒤바뀐 두 남녀의 이야기를 그린 판타지 무협.",
  },
];
