INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('후아유 : 학교 2015','Who Are You: School 2015',ARRAY['후아유 : 학교 2015','Who Are You: School 2015','후아유:학교2015']::text[],2015,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('굿 닥터','Good Doctor',ARRAY['굿 닥터','Good Doctor','굿닥터']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('내 여자친구는 구미호','My Girlfriend Is a Nine-Tailed Fox',ARRAY['내 여자친구는 구미호','My Girlfriend Is a Nine-Tailed Fox','내여자친구는구미호']::text[],2010,'SBS',ARRAY['Drama']::text[],'published'),
('개인의 취향','Personal Taste',ARRAY['개인의 취향','Personal Taste','개인의취향']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('궁','Princess Hours',ARRAY['궁','Princess Hours']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내 남편과 결혼해줘','Marry My Husband',ARRAY['내 남편과 결혼해줘','Marry My Husband','내남편과결혼해줘']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('너도 인간이니','Are You Human?',ARRAY['너도 인간이니','Are You Human?','너도인간이니']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('함부로 애틋하게','Uncontrollably Fond',ARRAY['함부로 애틋하게','Uncontrollably Fond','함부로애틋하게']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('아이리스','Iris',ARRAY['아이리스','Iris']::text[],2009,'KBS2',ARRAY['Drama']::text[],'published'),
('마이걸','My Girl',ARRAY['마이걸','My Girl']::text[],2005,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('풀하우스','Full House',ARRAY['풀하우스','Full House']::text[],2004,'KBS2',ARRAY['Drama']::text[],'published'),
('폭싹 속았수다','When Life Gives You Tangerines',ARRAY['폭싹 속았수다','When Life Gives You Tangerines','폭싹속았수다']::text[],2025,'Netflix',ARRAY['가족','로맨스']::text[],'published'),
('더 글로리','The Glory',ARRAY['더 글로리','The Glory','더글로리']::text[],2022,'Netflix',ARRAY['스릴러','복수']::text[],'published'),
('슬기로운 의사생활','Hospital Playlist',ARRAY['슬기로운 의사생활','Hospital Playlist','슬기로운의사생활']::text[],2020,'tvN',ARRAY['의료','드라마']::text[],'published'),
('SKY 캐슬','SKY Castle',ARRAY['SKY 캐슬','SKY Castle','SKY캐슬']::text[],2018,'JTBC',ARRAY['드라마','스릴러']::text[],'published'),
('수상한 파트너','Suspicious Partner',ARRAY['수상한 파트너','Suspicious Partner','수상한파트너']::text[],2017,'SBS',ARRAY['Drama']::text[],'published'),
('마녀보감','Secret Healer',ARRAY['마녀보감','Secret Healer']::text[],2016,'JTBC',ARRAY['Drama']::text[],'published'),
('볼트론: 전설 속의 수호자','Voltron: Legendary Defender',ARRAY['볼트론: 전설 속의 수호자','Voltron: Legendary Defender','볼트론:전설속의수호자']::text[],2016,'Netflix',ARRAY['Drama']::text[],'published'),
('용팔이','Yong-pal',ARRAY['용팔이','Yong-pal']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('옥탑방 왕세자','Rooftop Prince',ARRAY['옥탑방 왕세자','Rooftop Prince','옥탑방왕세자']::text[],2012,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('로보카폴리','Robocar Poli',ARRAY['로보카폴리','Robocar Poli']::text[],2011,'EBS 1TV',ARRAY['Drama']::text[],'published'),
('성균관 스캔들','Sungkyunkwan Scandal',ARRAY['성균관 스캔들','Sungkyunkwan Scandal','성균관스캔들']::text[],2010,'KBS2',ARRAY['사극','로맨스']::text[],'published'),
('해신','Emperor of the Sea',ARRAY['해신','Emperor of the Sea']::text[],2004,'KBS2',ARRAY['Drama']::text[],'published'),
('천국의 계단','Stairway to Heaven',ARRAY['천국의 계단','Stairway to Heaven','천국의계단']::text[],2003,'SBS',ARRAY['Drama']::text[],'published'),
('가을동화','Autumn in My Heart',ARRAY['가을동화','Autumn in My Heart']::text[],2000,'KBS2',ARRAY['로맨스']::text[],'published'),
('허준','Hur Jun',ARRAY['허준','Hur Jun']::text[],1999,'MBC',ARRAY['Drama']::text[],'published'),
('참교육','Teach You a Lesson',ARRAY['참교육','Teach You a Lesson']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('빅마우스','Big Mouth',ARRAY['빅마우스','Big Mouth']::text[],2022,'MBC',ARRAY['Drama']::text[],'published'),
('청춘기록','Record of Youth',ARRAY['청춘기록','Record of Youth']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('구미호뎐','Tale of the Nine Tailed',ARRAY['구미호뎐','Tale of the Nine Tailed']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('경이로운 소문','The Uncanny Counter',ARRAY['경이로운 소문','The Uncanny Counter','경이로운소문']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('백일의 낭군님','100 Days My Prince',ARRAY['백일의 낭군님','100 Days My Prince','백일의낭군님']::text[],2018,'TVN (Southeast Asia)',ARRAY['Drama']::text[],'published'),
('밥 잘 사주는 예쁜 누나','Something in the Rain',ARRAY['밥 잘 사주는 예쁜 누나','Something in the Rain','밥잘사주는예쁜누나']::text[],2018,'JTBC',ARRAY['로맨스']::text[],'published'),
('시카고 타자기','Chicago Typewriter',ARRAY['시카고 타자기','Chicago Typewriter','시카고타자기']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('레인보우 루비','Rainbow Ruby',ARRAY['레인보우 루비','Rainbow Ruby','레인보우루비']::text[],2016,'EBS 1TV',ARRAY['Drama']::text[],'published'),
('쇼핑왕 루이','Shopaholic Louis',ARRAY['쇼핑왕 루이','Shopaholic Louis','쇼핑왕루이']::text[],2016,'MBC',ARRAY['Drama']::text[],'published'),
('감각남녀','A Girl Who Sees Smells',ARRAY['감각남녀','A Girl Who Sees Smells']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('육룡이 나르샤','Six Flying Dragons',ARRAY['육룡이 나르샤','Six Flying Dragons','육룡이나르샤']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('아랑사또전','Arang and the Magistrate',ARRAY['아랑사또전','Arang and the Magistrate']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('보고싶다','Missing You',ARRAY['보고싶다','Missing You']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('세상 어디에도 없는 착한남자','The Innocent Man',ARRAY['세상 어디에도 없는 착한남자','The Innocent Man','세상어디에도없는착한남자']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('제빵왕 김탁구','Bread, Love and Dreams',ARRAY['제빵왕 김탁구','Bread, Love and Dreams','제빵왕김탁구']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('엄마친구아들','Love Next Door',ARRAY['엄마친구아들','Love Next Door']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('기생수: 더 그레이','Parasyte: The Grey',ARRAY['기생수: 더 그레이','Parasyte: The Grey','기생수:더그레이']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('이재, 곧 죽습니다','Death''s Game',ARRAY['이재, 곧 죽습니다','Death''s Game','이재,곧죽습니다']::text[],2023,'TVING',ARRAY['Drama']::text[],'published'),
('킹더랜드','King the Land',ARRAY['킹더랜드','King the Land']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('마이데몬','My Demon',ARRAY['마이데몬','My Demon']::text[],2023,'SBS',ARRAY['Drama']::text[],'published'),
('기상청 사람들: 사내연애 잔혹사 편','Forecasting Love and Weather',ARRAY['기상청 사람들: 사내연애 잔혹사 편','Forecasting Love and Weather','기상청사람들:사내연애잔혹사편']::text[],2022,'JTBC',ARRAY['Drama']::text[],'published'),
('작은 아씨들','Little Women',ARRAY['작은 아씨들','Little Women','작은아씨들']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('슈룹','Under the Queen''s Umbrella',ARRAY['슈룹','Under the Queen''s Umbrella']::text[],2022,'tvN',ARRAY['사극','코미디']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);