INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('일타 스캔들','Crash Course in Romance',ARRAY['일타 스캔들','Crash Course in Romance','일타스캔들']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('반짝이는 워터멜론','Twinkling Watermelon',ARRAY['반짝이는 워터멜론','Twinkling Watermelon','반짝이는워터멜론']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('소년심판','Juvenile Justice',ARRAY['소년심판','Juvenile Justice']::text[],2022,'Netflix',ARRAY['법률','드라마']::text[],'published'),
('재벌집 막내아들','Reborn Rich',ARRAY['재벌집 막내아들','Reborn Rich','재벌집막내아들']::text[],2022,'JTBC',ARRAY['드라마','판타지']::text[],'published'),
('약한영웅 Class 1','Weak Hero Class 1',ARRAY['약한영웅 Class 1','Weak Hero Class 1','약한영웅Class1']::text[],2022,'Netflix',ARRAY['액션','청춘']::text[],'published'),
('마우스','Mouse',ARRAY['마우스','Mouse']::text[],2021,'tvN',ARRAY['스릴러']::text[],'published'),
('악마판사','The Devil Judge',ARRAY['악마판사','The Devil Judge']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('아스달 연대기','Arthdal Chronicles',ARRAY['아스달 연대기','Arthdal Chronicles','아스달연대기']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('타인은 지옥이다','Hell Is Other People',ARRAY['타인은 지옥이다','Hell Is Other People','타인은지옥이다']::text[],2019,'OCN',ARRAY['Drama']::text[],'published'),
('좋아하면 울리는','Love Alarm',ARRAY['좋아하면 울리는','Love Alarm','좋아하면울리는']::text[],2019,'Netflix',ARRAY['Drama']::text[],'published'),
('로맨스는 별책부록','Romance Is a Bonus Book',ARRAY['로맨스는 별책부록','Romance Is a Bonus Book','로맨스는별책부록']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('조선로코 녹두전','The Tale of Nokdu',ARRAY['조선로코 녹두전','The Tale of Nokdu','조선로코녹두전']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('알함브라 궁전의 추억','Memories of the Alhambra',ARRAY['알함브라 궁전의 추억','Memories of the Alhambra','알함브라궁전의추억']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('라디오 로맨스','Radio Romance',ARRAY['라디오 로맨스','Radio Romance','라디오로맨스']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('으라차차 와이키키','Welcome to Waikiki',ARRAY['으라차차 와이키키','Welcome to Waikiki','으라차차와이키키']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published'),
('블랙','Black',ARRAY['블랙','Black']::text[],2017,'OCN',ARRAY['Drama']::text[],'published'),
('7일의 왕비','Queen for Seven Days',ARRAY['7일의 왕비','Queen for Seven Days','7일의왕비']::text[],2017,'KBS2',ARRAY['Drama']::text[],'published'),
('비밀의 숲','Stranger',ARRAY['비밀의 숲','Stranger','비밀의숲']::text[],2017,'tvN',ARRAY['스릴러','법률']::text[],'published'),
('내일 그대와','Tomorrow With You',ARRAY['내일 그대와','Tomorrow With You','내일그대와']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('치즈인더트랩','Cheese in the Trap',ARRAY['치즈인더트랩','Cheese in the Trap']::text[],2016,'tvN',ARRAY['로맨스']::text[],'published'),
('몰랑이','Molang',ARRAY['몰랑이','Molang']::text[],2016,'Disney Jr.',ARRAY['Drama']::text[],'published'),
('너를 기억해','Hello Monster',ARRAY['너를 기억해','Hello Monster','너를기억해']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('밤을 걷는 선비','Scholar Who Walks the Night',ARRAY['밤을 걷는 선비','Scholar Who Walks the Night','밤을걷는선비']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('퐁당퐁당 Love','Splash Splash Love',ARRAY['퐁당퐁당 Love','Splash Splash Love','퐁당퐁당Love']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('맨도롱 또똣','Warm and Cozy',ARRAY['맨도롱 또똣','Warm and Cozy','맨도롱또똣']::text[],2015,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내겐 너무 사랑스러운 그녀','My Lovely Girl',ARRAY['내겐 너무 사랑스러운 그녀','My Lovely Girl','내겐너무사랑스러운그녀']::text[],2014,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('야경꾼 일지','Night Watchman''s Journal',ARRAY['야경꾼 일지','Night Watchman''s Journal','야경꾼일지']::text[],2014,'MBC',ARRAY['Drama']::text[],'published'),
('예쁜 남자','Bel Ami',ARRAY['예쁜 남자','Bel Ami','예쁜남자']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('불의 여신 정이','Goddess of Fire',ARRAY['불의 여신 정이','Goddess of Fire','불의여신정이']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('응답하라 1994','Reply 1994',ARRAY['응답하라 1994','Reply 1994','응답하라1994']::text[],2013,'tvN',ARRAY['로맨스','청춘']::text[],'published'),
('그 겨울, 바람이 분다','That Winter, The Wind Blows',ARRAY['그 겨울, 바람이 분다','That Winter, The Wind Blows','그겨울,바람이분다']::text[],2013,'Seoul Broadcasting System',ARRAY['로맨스']::text[],'published'),
('신사의 품격','A Gentleman''s Dignity',ARRAY['신사의 품격','A Gentleman''s Dignity','신사의품격']::text[],2012,'Seoul Broadcasting System',ARRAY['로맨스','코미디']::text[],'published'),
('빅','Big',ARRAY['빅','Big']::text[],2012,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('인현왕후의 남자','Queen In-Hyun''s Man',ARRAY['인현왕후의 남자','Queen In-Hyun''s Man','인현왕후의남자']::text[],2012,'tvN',ARRAY['Drama']::text[],'published'),
('최고의 사랑','The Greatest Love',ARRAY['최고의 사랑','The Greatest Love','최고의사랑']::text[],2011,'MBC',ARRAY['Drama']::text[],'published'),
('추노','Chuno',ARRAY['추노','Chuno']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('찬란한 유산','Brilliant Legacy',ARRAY['찬란한 유산','Brilliant Legacy','찬란한유산']::text[],2009,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('다모','Damo',ARRAY['다모','Damo']::text[],2003,'MBC',ARRAY['Drama']::text[],'published'),
('여름향기','Summer Scent',ARRAY['여름향기','Summer Scent']::text[],2003,'KBS2',ARRAY['Drama']::text[],'published'),
('상도','The Merchant of Joseon',ARRAY['상도','The Merchant of Joseon']::text[],2001,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('폭군의 셰프','Bon Appétit, Your Majesty',ARRAY['폭군의 셰프','Bon Appétit, Your Majesty','폭군의셰프']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('다 이루어질지니','Genie, Make a Wish',ARRAY['다 이루어질지니','Genie, Make a Wish','다이루어질지니']::text[],2025,'Netflix',ARRAY['Drama']::text[],'published'),
('굿보이','Good Boy',ARRAY['굿보이','Good Boy']::text[],2025,'JTBC',ARRAY['Drama']::text[],'published'),
('별들에게 물어봐','When the Stars Gossip',ARRAY['별들에게 물어봐','When the Stars Gossip','별들에게물어봐']::text[],2025,'tvN',ARRAY['Drama']::text[],'published'),
('더 에이트 쇼','The 8 Show',ARRAY['더 에이트 쇼','The 8 Show','더에이트쇼']::text[],2024,'Netflix',ARRAY['Drama']::text[],'published'),
('힙(HIP)하게','Behind your Touch',ARRAY['힙(HIP)하게','Behind your Touch']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('정신병동에도 아침이 와요','Daily Dose of Sunshine',ARRAY['정신병동에도 아침이 와요','Daily Dose of Sunshine','정신병동에도아침이와요']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이두나!','Doona!',ARRAY['이두나!','Doona!']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이번 생도 잘 부탁해','See You in My 19th Life',ARRAY['이번 생도 잘 부탁해','See You in My 19th Life','이번생도잘부탁해']::text[],2023,'tvN',ARRAY['Drama']::text[],'published'),
('웰컴투 삼달리','Welcome to Samdalri',ARRAY['웰컴투 삼달리','Welcome to Samdalri','웰컴투삼달리']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);