INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('어게인 마이 라이프','Again My Life',ARRAY['어게인 마이 라이프','Again My Life','어게인마이라이프']::text[],2022,'SBS',ARRAY['Drama']::text[],'published'),
('고스트 닥터','Ghost Doctor',ARRAY['고스트 닥터','Ghost Doctor','고스트닥터']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('무브 투 헤븐: 나는 유품정리사입니다','Move to Heaven',ARRAY['무브 투 헤븐: 나는 유품정리사입니다','Move to Heaven','무브투헤븐:나는유품정리사입니다']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('나빌레라','Navillera',ARRAY['나빌레라','Navillera']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('알고있지만','Nevertheless',ARRAY['알고있지만','Nevertheless']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('아기상어 올리와 윌리엄','Baby Shark''s Big Show!',ARRAY['아기상어 올리와 윌리엄','Baby Shark''s Big Show!','아기상어올리와윌리엄']::text[],2020,'Nickelodeon',ARRAY['Drama']::text[],'published'),
('편의점 샛별이','Backstreet Rookie',ARRAY['편의점 샛별이','Backstreet Rookie','편의점샛별이']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('도도솔솔라라솔','Do Do Sol Sol La La Sol',ARRAY['도도솔솔라라솔','Do Do Sol Sol La La Sol']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('인간수업','Extracurricular',ARRAY['인간수업','Extracurricular']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('나 홀로 그대','My Holo Love',ARRAY['나 홀로 그대','My Holo Love','나홀로그대']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('쌍갑포차','Mystic Pop-up Bar',ARRAY['쌍갑포차','Mystic Pop-up Bar']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('날씨가 좋으면 찾아가겠어요','When the Weather Is Fine',ARRAY['날씨가 좋으면 찾아가겠어요','When the Weather Is Fine','날씨가좋으면찾아가겠어요']::text[],2020,'JTBC',ARRAY['Drama']::text[],'published'),
('어비스','Abyss',ARRAY['어비스','Abyss']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('우아한 가','Graceful Family',ARRAY['우아한 가','Graceful Family','우아한가']::text[],2019,'Maeil Broadcasting Network',ARRAY['Drama']::text[],'published'),
('검색어를 입력하세요: www','Search: WWW',ARRAY['검색어를 입력하세요: www','Search: WWW','검색어를입력하세요:www']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('열혈사제','The Fiery Priest',ARRAY['열혈사제','The Fiery Priest']::text[],2019,'SBS',ARRAY['Drama']::text[],'published'),
('무법 변호사','Lawless Lawyer',ARRAY['무법 변호사','Lawless Lawyer','무법변호사']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('나의 아저씨','My Mister',ARRAY['나의 아저씨','My Mister','나의아저씨']::text[],2018,'tvN',ARRAY['드라마']::text[],'published'),
('내 뒤에 테리우스','My Secret Terrius',ARRAY['내 뒤에 테리우스','My Secret Terrius','내뒤에테리우스']::text[],2018,'MBC',ARRAY['Drama']::text[],'published'),
('서른이지만 열일곱입니다','Still 17',ARRAY['서른이지만 열일곱입니다','Still 17','서른이지만열일곱입니다']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('슈츠','Suits',ARRAY['슈츠','Suits']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('황후의 품격','The Last Empress',ARRAY['황후의 품격','The Last Empress','황후의품격']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('여우각시별','Where Stars Land',ARRAY['여우각시별','Where Stars Land']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('사랑의 온도','Temperature of Love',ARRAY['사랑의 온도','Temperature of Love','사랑의온도']::text[],2017,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('하백의 신부 2017','The Bride of Habaek',ARRAY['하백의 신부 2017','The Bride of Habaek','하백의신부2017']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('보이스','Voice',ARRAY['보이스','Voice']::text[],2017,'OCN',ARRAY['스릴러']::text[],'published'),
('또 오해영','Another Miss Oh',ARRAY['또 오해영','Another Miss Oh','또오해영']::text[],2016,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('무림학교','Moorim School',ARRAY['무림학교','Moorim School']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('우리 옆집에 EXO가 산다','EXO Next Door',ARRAY['우리 옆집에 EXO가 산다','EXO Next Door','우리옆집에EXO가산다']::text[],2015,'JTBC2',ARRAY['Drama']::text[],'published'),
('하이드 지킬, 나','Jekyll and Me',ARRAY['하이드 지킬, 나','Jekyll and Me','하이드지킬,나']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('가면','Mask',ARRAY['가면','Mask']::text[],2015,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('리멤버 - 아들의 전쟁','Remember: War of the Son',ARRAY['리멤버 - 아들의 전쟁','Remember: War of the Son','리멤버-아들의전쟁']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('조선 총잡이','Gunman in Joseon',ARRAY['조선 총잡이','Gunman in Joseon','조선총잡이']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('하이스쿨 러브온','Hi! School: Love On',ARRAY['하이스쿨 러브온','Hi! School: Love On','하이스쿨러브온']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('괜찮아, 사랑이야','It''s Okay, That''s Love',ARRAY['괜찮아, 사랑이야','It''s Okay, That''s Love','괜찮아,사랑이야']::text[],2014,'SBS',ARRAY['Drama']::text[],'published'),
('가족끼리 왜 이래','What Happens to My Family?',ARRAY['가족끼리 왜 이래','What Happens to My Family?','가족끼리왜이래']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('더킹2Hearts','The King 2 Hearts',ARRAY['더킹2Hearts','The King 2 Hearts']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('마의','The King''s Doctor',ARRAY['마의','The King''s Doctor']::text[],2012,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내게 거짓말을 해봐','Lie to Me',ARRAY['내게 거짓말을 해봐','Lie to Me','내게거짓말을해봐']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('공주의 남자','The Princess'' Man',ARRAY['공주의 남자','The Princess'' Man','공주의남자']::text[],2011,'KBS2',ARRAY['Drama']::text[],'published'),
('대물','Big Thing',ARRAY['대물','Big Thing']::text[],2010,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('매리는 외박중','Mary Stayed Out All Night',ARRAY['매리는 외박중','Mary Stayed Out All Night','매리는외박중']::text[],2010,'KBS2',ARRAY['Drama']::text[],'published'),
('황진이','Hwang Jini',ARRAY['황진이','Hwang Jini']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('봄의 왈츠','Spring Waltz',ARRAY['봄의 왈츠','Spring Waltz','봄의왈츠']::text[],2006,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('킬러들의 쇼핑몰','A Shop for Killers',ARRAY['킬러들의 쇼핑몰','A Shop for Killers','킬러들의쇼핑몰']::text[],2024,'Star',ARRAY['Drama']::text[],'published'),
('낮과 밤이 다른 그녀','Miss Night and Day',ARRAY['낮과 밤이 다른 그녀','Miss Night and Day','낮과밤이다른그녀']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('피라미드 게임','Pyramid Game',ARRAY['피라미드 게임','Pyramid Game','피라미드게임']::text[],2024,'TVING',ARRAY['Drama']::text[],'published'),
('히어로는 아닙니다만','The Atypical Family',ARRAY['히어로는 아닙니다만','The Atypical Family','히어로는아닙니다만']::text[],2024,'JTBC',ARRAY['Drama']::text[],'published'),
('너의 시간 속으로','A Time Called You',ARRAY['너의 시간 속으로','A Time Called You','너의시간속으로']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('택배기사','Black Knight',ARRAY['택배기사','Black Knight']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);