INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('셀러브리티','Celebrity',ARRAY['셀러브리티','Celebrity']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('이 연애는 불가항력','Destined With You',ARRAY['이 연애는 불가항력','Destined With You','이연애는불가항력']::text[],2023,'JTBC',ARRAY['Drama']::text[],'published'),
('연애대전','Love to Hate You',ARRAY['연애대전','Love to Hate You']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('마스크걸','Mask Girl',ARRAY['마스크걸','Mask Girl']::text[],2023,'Netflix',ARRAY['Drama']::text[],'published'),
('천원짜리 변호사','One Dollar Lawyer',ARRAY['천원짜리 변호사','One Dollar Lawyer','천원짜리변호사']::text[],2022,'SBS',ARRAY['Drama']::text[],'published'),
('우리들의 블루스','Our Blues',ARRAY['우리들의 블루스','Our Blues','우리들의블루스']::text[],2022,'tvN',ARRAY['Drama']::text[],'published'),
('썸바디','Somebody',ARRAY['썸바디','Somebody']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('안나라수마나라','The Sound of Magic',ARRAY['안나라수마나라','The Sound of Magic']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('간 떨어지는 동거','My Roommate is a Gumiho',ARRAY['간 떨어지는 동거','My Roommate is a Gumiho','간떨어지는동거']::text[],2021,'tvN',ARRAY['Drama']::text[],'published'),
('원 더 우먼','One the Woman',ARRAY['원 더 우먼','One the Woman','원더우먼']::text[],2021,'SBS',ARRAY['Drama']::text[],'published'),
('대박부동산','Sell Your Haunted House',ARRAY['대박부동산','Sell Your Haunted House']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('오월의 청춘','Youth of May',ARRAY['오월의 청춘','Youth of May','오월의청춘']::text[],2021,'KBS2',ARRAY['Drama']::text[],'published'),
('앨리스','Alice',ARRAY['앨리스','Alice']::text[],2020,'SBS',ARRAY['Drama']::text[],'published'),
('그 남자의 기억법','Find Me in Your Memory',ARRAY['그 남자의 기억법','Find Me in Your Memory','그남자의기억법']::text[],2020,'MBC',ARRAY['Drama']::text[],'published'),
('키포와 신기한 동물들','Kipo and the Age of Wonderbeasts',ARRAY['키포와 신기한 동물들','Kipo and the Age of Wonderbeasts','키포와신기한동물들']::text[],2020,'Netflix',ARRAY['Drama']::text[],'published'),
('어서와','Welcome',ARRAY['어서와','Welcome']::text[],2020,'KBS2',ARRAY['Drama']::text[],'published'),
('닥터 프리즈너','Doctor Prisoner',ARRAY['닥터 프리즈너','Doctor Prisoner','닥터프리즈너']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('열여덟의 순간','The Moment of 18',ARRAY['열여덟의 순간','The Moment of 18','열여덟의순간']::text[],2019,'JTBC',ARRAY['Drama']::text[],'published'),
('사의 찬미','The Hymn of Death',ARRAY['사의 찬미','The Hymn of Death','사의찬미']::text[],2018,'SBS',ARRAY['Drama']::text[],'published'),
('크리미널 마인드','Criminal Minds',ARRAY['크리미널 마인드','Criminal Minds','크리미널마인드']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('최고의 한방','Hit the Top',ARRAY['최고의 한방','Hit the Top','최고의한방']::text[],2017,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('그녀는 거짓말을 너무 사랑해','The Liar and His Lover',ARRAY['그녀는 거짓말을 너무 사랑해','The Liar and His Lover','그녀는거짓말을너무사랑해']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('돌아와요 아저씨','Come Back Mister',ARRAY['돌아와요 아저씨','Come Back Mister','돌아와요아저씨']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('사랑하는 은동아','Beloved Eun-dong',ARRAY['사랑하는 은동아','Beloved Eun-dong','사랑하는은동아']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('순정에 반하다','Falling for Innocence',ARRAY['순정에 반하다','Falling for Innocence','순정에반하다']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('상류사회','High Society',ARRAY['상류사회','High Society']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('하녀들','Maids',ARRAY['하녀들','Maids']::text[],2015,'JTBC',ARRAY['Drama']::text[],'published'),
('두번째 스무살','Second 20s',ARRAY['두번째 스무살','Second 20s','두번째스무살']::text[],2015,'tvN',ARRAY['Drama']::text[],'published'),
('트라이앵글','Triangle',ARRAY['트라이앵글','Triangle']::text[],2014,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('7급 공무원','7th Grade Civil Servant',ARRAY['7급 공무원','7th Grade Civil Servant','7급공무원']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('야왕','Queen of Ambition',ARRAY['야왕','Queen of Ambition']::text[],2013,'SBS',ARRAY['Drama']::text[],'published'),
('투웍스','Two Weeks',ARRAY['투웍스','Two Weeks']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('천일의 약속','A Thousand Days'' Promise',ARRAY['천일의 약속','A Thousand Days'' Promise','천일의약속']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('꽃미남 라면가게','Flower Boy Ramen Shop',ARRAY['꽃미남 라면가게','Flower Boy Ramen Shop','꽃미남라면가게']::text[],2011,'tvN',ARRAY['Drama']::text[],'published'),
('영광의 재인','Glory Jane',ARRAY['영광의 재인','Glory Jane','영광의재인']::text[],2011,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('계백','Gyebaek',ARRAY['계백','Gyebaek']::text[],2011,'MBC',ARRAY['Drama']::text[],'published'),
('주간 아이돌','Weekly Idol',ARRAY['주간 아이돌','Weekly Idol','주간아이돌']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('아테나: 전쟁의 여신','Athena: Goddess of War',ARRAY['아테나: 전쟁의 여신','Athena: Goddess of War','아테나:전쟁의여신']::text[],2010,'SBS',ARRAY['Drama']::text[],'published'),
('아가씨를 부탁해','My Fair Lady',ARRAY['아가씨를 부탁해','My Fair Lady','아가씨를부탁해']::text[],2009,'KBS2',ARRAY['Drama']::text[],'published'),
('에덴의 동쪽','East of Eden',ARRAY['에덴의 동쪽','East of Eden','에덴의동쪽']::text[],2008,'MBC',ARRAY['Drama']::text[],'published'),
('우리 결혼했어요','We Got Married',ARRAY['우리 결혼했어요','We Got Married','우리결혼했어요']::text[],2008,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('왕과 나','The King and I',ARRAY['왕과 나','The King and I','왕과나']::text[],2007,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('개와 늑대의 시간','Time Between Dog and Wolf',ARRAY['개와 늑대의 시간','Time Between Dog and Wolf','개와늑대의시간']::text[],2007,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('환상의 커플','Couple or Trouble',ARRAY['환상의 커플','Couple or Trouble','환상의커플']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('별은 내 가슴에','Star in My Heart',ARRAY['별은 내 가슴에','Star in My Heart','별은내가슴에']::text[],1997,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('첫사랑','First Love',ARRAY['첫사랑','First Love']::text[],1996,'KBS2',ARRAY['Drama']::text[],'published'),
('여명의 눈동자','Eyes of Dawn',ARRAY['여명의 눈동자','Eyes of Dawn','여명의눈동자']::text[],1991,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('21세기 대군부인','Perfect Crown',ARRAY['21세기 대군부인','Perfect Crown','21세기대군부인']::text[],2026,'MBC',ARRAY['Drama']::text[],'published'),
('동궁','The East Palace',ARRAY['동궁','The East Palace']::text[],2026,'Netflix',ARRAY['Drama']::text[],'published'),
('에스콰이어: 변호사를 꿈꾸는 변호사들','Beyond the Bar',ARRAY['에스콰이어: 변호사를 꿈꾸는 변호사들','Beyond the Bar','에스콰이어:변호사를꿈꾸는변호사들']::text[],2025,'JTBC',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en) OR d.title_kr = v.title_kr
);