INSERT INTO public.dramas (title_kr, title_en, aliases, year, network, genres, status)
SELECT * FROM (VALUES
('오징어 게임','Squid Game',ARRAY['오징어 게임','Squid Game','오징어게임']::text[],2021,'Netflix',ARRAY['스릴러','액션']::text[],'published'),
('쓸쓸하고 찬란하神 도깨비','Goblin',ARRAY['쓸쓸하고 찬란하神 도깨비','Goblin','쓸쓸하고찬란하神도깨비']::text[],2016,'tvN',ARRAY['판타지']::text[],'published'),
('낭만닥터 김사부','Romantic Doctor, Teacher Kim',ARRAY['낭만닥터 김사부','Romantic Doctor, Teacher Kim','낭만닥터김사부']::text[],2016,'SBS',ARRAY['의료']::text[],'published'),
('킬미힐미','Kill Me, Heal Me',ARRAY['킬미힐미','Kill Me, Heal Me']::text[],2015,'MBC',ARRAY['로맨스','코미디']::text[],'published'),
('해를 품은 달','The Moon Embracing the Sun',ARRAY['해를 품은 달','The Moon Embracing the Sun','해를품은달']::text[],2012,'MBC',ARRAY['사극','로맨스']::text[],'published'),
('내 이름은 김삼순','My Name Is Kim Sam-soon',ARRAY['내 이름은 김삼순','My Name Is Kim Sam-soon','내이름은김삼순']::text[],2005,'MBC',ARRAY['로맨스','코미디']::text[],'published'),
('대장금','Jewel in the Palace',ARRAY['대장금','Jewel in the Palace']::text[],2003,'MBC',ARRAY['사극']::text[],'published'),
('사랑의 불시착','Crash Landing on You',ARRAY['사랑의 불시착','Crash Landing on You','사랑의불시착']::text[],2019,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('펜트하우스','The Penthouse: War in Life',ARRAY['펜트하우스','The Penthouse: War in Life']::text[],2020,'SBS',ARRAY['스릴러','드라마']::text[],'published'),
('여신강림','True Beauty',ARRAY['여신강림','True Beauty']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('쓸쓸하고 찬란하神 - 도깨비','Guardian: The Lonely and Great God',ARRAY['쓸쓸하고 찬란하神 - 도깨비','Guardian: The Lonely and Great God','쓸쓸하고찬란하神-도깨비']::text[],2016,'tvN',ARRAY['판타지','로맨스']::text[],'published'),
('태양의 후예','Descendants of the Sun',ARRAY['태양의 후예','Descendants of the Sun','태양의후예']::text[],2016,'KBS2',ARRAY['로맨스','액션']::text[],'published'),
('사이코지만 괜찮아','It''s Okay to Not Be Okay',ARRAY['사이코지만 괜찮아','It''s Okay to Not Be Okay','사이코지만괜찮아']::text[],2020,'tvN',ARRAY['로맨스','드라마']::text[],'published'),
('꽃보다 남자','Boys Over Flowers',ARRAY['꽃보다 남자','Boys Over Flowers','꽃보다남자']::text[],2009,'KBS2',ARRAY['로맨스','청춘']::text[],'published'),
('빈센조','Vincenzo',ARRAY['빈센조','Vincenzo']::text[],2021,'tvN',ARRAY['범죄','코미디']::text[],'published'),
('설강화 : snowdrop','Snowdrop',ARRAY['설강화 : snowdrop','Snowdrop','설강화:snowdrop']::text[],2021,'JTBC',ARRAY['Drama']::text[],'published'),
('철인왕후','Mr. Queen',ARRAY['철인왕후','Mr. Queen']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('호텔 델루나','Hotel del Luna',ARRAY['호텔 델루나','Hotel del Luna','호텔델루나']::text[],2019,'tvN',ARRAY['판타지','로맨스']::text[],'published'),
('지금 우리 학교는','All of Us Are Dead',ARRAY['지금 우리 학교는','All of Us Are Dead','지금우리학교는']::text[],2022,'Netflix',ARRAY['스릴러','좀비']::text[],'published'),
('부부의 세계','The World of the Married',ARRAY['부부의 세계','The World of the Married','부부의세계']::text[],2020,'JTBC',ARRAY['드라마','스릴러']::text[],'published'),
('상속자들','The Heirs',ARRAY['상속자들','The Heirs']::text[],2013,'Seoul Broadcasting System',ARRAY['로맨스','청춘']::text[],'published'),
('스타트업','Start-Up',ARRAY['스타트업','Start-Up']::text[],2020,'tvN',ARRAY['로맨스','청춘']::text[],'published'),
('별에서 온 그대','My Love from the Star',ARRAY['별에서 온 그대','My Love from the Star','별에서온그대']::text[],2013,'SBS',ARRAY['Drama']::text[],'published'),
('달의 연인 - 보보경심 려','Moon Lovers: Scarlet Heart Ryeo',ARRAY['달의 연인 - 보보경심 려','Moon Lovers: Scarlet Heart Ryeo','달의연인-보보경심려']::text[],2016,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('푸른 바다의 전설','The Legend of the Blue Sea',ARRAY['푸른 바다의 전설','The Legend of the Blue Sea','푸른바다의전설']::text[],2016,'SBS',ARRAY['Drama']::text[],'published'),
('김비서가 왜 그럴까','What''s Wrong with Secretary Kim',ARRAY['김비서가 왜 그럴까','What''s Wrong with Secretary Kim','김비서가왜그럴까']::text[],2018,'TVN (Southeast Asia)',ARRAY['로맨스','코미디']::text[],'published'),
('더 킹 : 영원의 군주','The King: Eternal Monarch',ARRAY['더 킹 : 영원의 군주','The King: Eternal Monarch','더킹:영원의군주']::text[],2015,'SBS',ARRAY['Drama']::text[],'published'),
('로봇이 아니야','I''m Not a Robot',ARRAY['로봇이 아니야','I''m Not a Robot','로봇이아니야']::text[],2017,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('더블유','W',ARRAY['더블유','W']::text[],2016,'MBC',ARRAY['Drama']::text[],'published'),
('오 나의 귀신님','Oh My Ghostess',ARRAY['오 나의 귀신님','Oh My Ghostess','오나의귀신님']::text[],2015,'tvN',ARRAY['Drama']::text[],'published'),
('프로듀사','Producer',ARRAY['프로듀사','Producer']::text[],2015,'KBS2',ARRAY['Drama']::text[],'published'),
('주몽','Jumong',ARRAY['주몽','Jumong']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('응답하라 1988','Reply 1988',ARRAY['응답하라 1988','Reply 1988','응답하라1988']::text[],2015,'tvN',ARRAY['로맨스','가족','코미디']::text[],'published'),
('드림하이','Dream High',ARRAY['드림하이','Dream High']::text[],2011,'KBS2',ARRAY['청춘','음악']::text[],'published'),
('겨울연가','Winter Sonata',ARRAY['겨울연가','Winter Sonata']::text[],2002,'KBS2',ARRAY['로맨스']::text[],'published'),
('어쩌다 발견한 하루','Extraordinary You',ARRAY['어쩌다 발견한 하루','Extraordinary You','어쩌다발견한하루']::text[],2019,'MBC',ARRAY['Drama']::text[],'published'),
('당신이 잠든 사이에','While You Were Sleeping',ARRAY['당신이 잠든 사이에','While You Were Sleeping','당신이잠든사이에']::text[],2017,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('구르미 그린 달빛','Love in the Moonlight',ARRAY['구르미 그린 달빛','Love in the Moonlight','구르미그린달빛']::text[],2016,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('역도요정 김복주','Weightlifting Fairy Kim Bok-Joo',ARRAY['역도요정 김복주','Weightlifting Fairy Kim Bok-Joo','역도요정김복주']::text[],2016,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('하이바이, 마마!','Hi Bye, Mama!',ARRAY['하이바이, 마마!','Hi Bye, Mama!','하이바이,마마!']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('이태원 클라쓰','Itaewon Class',ARRAY['이태원 클라쓰','Itaewon Class','이태원클라쓰']::text[],2020,'JTBC',ARRAY['드라마','청춘']::text[],'published'),
('시크릿 가든','Secret Garden',ARRAY['시크릿 가든','Secret Garden','시크릿가든']::text[],2010,'SBS',ARRAY['판타지','로맨스']::text[],'published'),
('커피프린스 1호점','The 1st Shop of Coffee Prince',ARRAY['커피프린스 1호점','The 1st Shop of Coffee Prince','커피프린스1호점']::text[],2007,'MBC',ARRAY['로맨스','코미디']::text[],'published'),
('종이의 집: 공동경제구역','Money Heist: Korea - Joint Economic Area',ARRAY['종이의 집: 공동경제구역','Money Heist: Korea - Joint Economic Area','종이의집:공동경제구역']::text[],2022,'Netflix',ARRAY['Drama']::text[],'published'),
('지옥','Hellbound',ARRAY['지옥','Hellbound']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('미스터 션샤인','Mr. Sunshine',ARRAY['미스터 션샤인','Mr. Sunshine','미스터션샤인']::text[],2018,'tvN',ARRAY['사극','로맨스']::text[],'published'),
('화유기','A Korean Odyssey',ARRAY['화유기','A Korean Odyssey']::text[],2017,'tvN',ARRAY['Drama']::text[],'published'),
('힘쎈여자 도봉순','Strong Woman Do Bong-soon',ARRAY['힘쎈여자 도봉순','Strong Woman Do Bong-soon','힘쎈여자도봉순']::text[],2017,'JTBC',ARRAY['Drama']::text[],'published'),
('화랑','Hwarang: The Poet Warrior Youth',ARRAY['화랑','Hwarang: The Poet Warrior Youth']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('스위트홈','Sweet Home',ARRAY['스위트홈','Sweet Home']::text[],2020,NULL,ARRAY['Drama']::text[],'published'),
('피노키오','Pinocchio',ARRAY['피노키오','Pinocchio']::text[],2014,'Seoul Broadcasting System',ARRAY['로맨스','드라마']::text[],'published'),
('넌 내게 반했어','Heartstrings',ARRAY['넌 내게 반했어','Heartstrings','넌내게반했어']::text[],2011,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('선덕여왕','Queen Seondeok',ARRAY['선덕여왕','Queen Seondeok']::text[],2009,'MBC',ARRAY['Drama']::text[],'published'),
('M Countdown','M Countdown',ARRAY['M Countdown','M Countdown','MCountdown']::text[],2004,'Mnet',ARRAY['Drama']::text[],'published'),
('빼꼼','Bernard',ARRAY['빼꼼','Bernard']::text[],2003,'British Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('뽀롱뽀롱 뽀로로','Pororo the Little Penguin',ARRAY['뽀롱뽀롱 뽀로로','Pororo the Little Penguin','뽀롱뽀롱뽀로로']::text[],2003,'Korea Educational Broadcasting System',ARRAY['Drama']::text[],'published'),
('눈물의 여왕','Queen of Tears',ARRAY['눈물의 여왕','Queen of Tears','눈물의여왕']::text[],2024,'tvN',ARRAY['로맨스','드라마']::text[],'published'),
('환혼','Alchemy of Souls',ARRAY['환혼','Alchemy of Souls']::text[],2022,'tvN',ARRAY['판타지','액션']::text[],'published'),
('사내맞선','Business Proposal',ARRAY['사내맞선','Business Proposal']::text[],2022,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('갯마을 차차차','Hometown Cha-Cha-Cha',ARRAY['갯마을 차차차','Hometown Cha-Cha-Cha','갯마을차차차']::text[],2021,'tvN',ARRAY['로맨스','코미디']::text[],'published'),
('마이 네임','My Name',ARRAY['마이 네임','My Name','마이네임']::text[],2021,'Netflix',ARRAY['Drama']::text[],'published'),
('시그널','Signal',ARRAY['시그널','Signal']::text[],2016,'tvN',ARRAY['스릴러','범죄']::text[],'published'),
('그녀는 예뻤다','She Was Pretty',ARRAY['그녀는 예뻤다','She Was Pretty','그녀는예뻤다']::text[],2015,'MBC',ARRAY['Drama']::text[],'published'),
('기황후','Empress Ki',ARRAY['기황후','Empress Ki']::text[],2013,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('너의 목소리가 들려','I Can Hear Your Voice',ARRAY['너의 목소리가 들려','I Can Hear Your Voice','너의목소리가들려']::text[],2013,'SBS',ARRAY['Drama']::text[],'published'),
('주군의 태양','Master''s Sun',ARRAY['주군의 태양','Master''s Sun','주군의태양']::text[],2013,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('라바','Larva',ARRAY['라바','Larva']::text[],2011,NULL,ARRAY['Drama']::text[],'published'),
('동이','Dong Yi',ARRAY['동이','Dong Yi']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('장난스런 키스','Playful Kiss',ARRAY['장난스런 키스','Playful Kiss','장난스런키스']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('미남이시네요','You''re Beautiful',ARRAY['미남이시네요','You''re Beautiful']::text[],2009,'TBS Television',ARRAY['Drama']::text[],'published'),
('분덕스','The Boondocks',ARRAY['분덕스','The Boondocks']::text[],2005,'Adult Swim',ARRAY['Drama']::text[],'published'),
('이상한 변호사 우영우','Extraordinary Attorney Woo',ARRAY['이상한 변호사 우영우','Extraordinary Attorney Woo','이상한변호사우영우']::text[],2022,'Netflix',ARRAY['법률','드라마']::text[],'published'),
('악의 꽃','Flower of Evil',ARRAY['악의 꽃','Flower of Evil','악의꽃']::text[],2020,'tvN',ARRAY['Drama']::text[],'published'),
('남자친구','Encounter',ARRAY['남자친구','Encounter']::text[],2018,'tvN',ARRAY['Drama']::text[],'published'),
('닥터스','The Doctors',ARRAY['닥터스','The Doctors']::text[],2016,'SBS',ARRAY['Drama']::text[],'published'),
('힐러','Healer',ARRAY['힐러','Healer']::text[],2014,'KBS2',ARRAY['Drama']::text[],'published'),
('시티헌터','City Hunter',ARRAY['시티헌터','City Hunter']::text[],2011,'Seoul Broadcasting System',ARRAY['Drama']::text[],'published'),
('단, 하나의 사랑','Angel''s Last Mission: Love',ARRAY['단, 하나의 사랑','Angel''s Last Mission: Love','단,하나의사랑']::text[],2019,'KBS2',ARRAY['Drama']::text[],'published'),
('진심이 닿다','Touch Your Heart',ARRAY['진심이 닿다','Touch Your Heart','진심이닿다']::text[],2019,'tvN',ARRAY['Drama']::text[],'published'),
('내 아이디는 강남미인','My ID is Gangnam Beauty',ARRAY['내 아이디는 강남미인','My ID is Gangnam Beauty','내아이디는강남미인']::text[],2018,'JTBC',ARRAY['Drama']::text[],'published'),
('후아유 : 학교 2015','Who Are You: School 2015',ARRAY['후아유 : 학교 2015','Who Are You: School 2015','후아유:학교2015']::text[],2015,'Korean Broadcasting System',ARRAY['Drama']::text[],'published'),
('굿 닥터','Good Doctor',ARRAY['굿 닥터','Good Doctor','굿닥터']::text[],2013,'KBS2',ARRAY['Drama']::text[],'published'),
('내 여자친구는 구미호','My Girlfriend Is a Nine-Tailed Fox',ARRAY['내 여자친구는 구미호','My Girlfriend Is a Nine-Tailed Fox','내여자친구는구미호']::text[],2010,'SBS',ARRAY['Drama']::text[],'published'),
('개인의 취향','Personal Taste',ARRAY['개인의 취향','Personal Taste','개인의취향']::text[],2010,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('궁','Princess Hours',ARRAY['궁','Princess Hours']::text[],2006,'Munhwa Broadcasting Corporation',ARRAY['Drama']::text[],'published'),
('내 남편과 결혼해줘','Marry My Husband',ARRAY['내 남편과 결혼해줘','Marry My Husband','내남편과결혼해줘']::text[],2024,'tvN',ARRAY['Drama']::text[],'published'),
('너도 인간이니','Are You Human?',ARRAY['너도 인간이니','Are You Human?','너도인간이니']::text[],2018,'KBS2',ARRAY['Drama']::text[],'published'),
('K2','The K2',ARRAY['K2','The K2']::text[],2016,'tvN',ARRAY['Drama']::text[],'published'),
('함부로 애틋하게','Uncontrollably Fond',ARRAY['함부로 애틋하게','Uncontrollably Fond','함부로애틋하게']::text[],2016,'KBS2',ARRAY['Drama']::text[],'published'),
('아이리스','Iris',ARRAY['아이리스','Iris']::text[],2009,'KBS2',ARRAY['Drama']::text[],'published')
) AS v(title_kr, title_en, aliases, year, network, genres, status)
WHERE NOT EXISTS (
  SELECT 1 FROM public.dramas d
  WHERE lower(d.title_en) = lower(v.title_en)
     OR d.title_kr = v.title_kr
);